// Code generated by ros2gen. DO NOT EDIT.

package rcl_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rcl_interfaces/srv/set_parameters_atomically.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("rcl_interfaces/SetParametersAtomically", SetParametersAtomicallyTypeSupport)
	humble.RegisterService("rcl_interfaces/srv/SetParametersAtomically", SetParametersAtomicallyTypeSupport)
}

type _SetParametersAtomicallyTypeSupport struct{}

func (s _SetParametersAtomicallyTypeSupport) Request() humble.MessageTypeSupport {
	return SetParametersAtomically_RequestTypeSupport
}

func (s _SetParametersAtomicallyTypeSupport) Response() humble.MessageTypeSupport {
	return SetParametersAtomically_ResponseTypeSupport
}

func (s _SetParametersAtomicallyTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rcl_interfaces__srv__SetParametersAtomically())
}

// Modifying this variable is undefined behavior.
var SetParametersAtomicallyTypeSupport humble.ServiceTypeSupport = _SetParametersAtomicallyTypeSupport{}

// SetParametersAtomicallyClient wraps humble.Client to provide type safe helper
// functions
type SetParametersAtomicallyClient struct {
	*humble.Client
}

// NewSetParametersAtomicallyClient creates and returns a new client for the
// SetParametersAtomically
func NewSetParametersAtomicallyClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*SetParametersAtomicallyClient, error) {
	client, err := node.NewClient(serviceName, SetParametersAtomicallyTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetParametersAtomicallyClient{client}, nil
}

func (s *SetParametersAtomicallyClient) Send(ctx context.Context, req *SetParametersAtomically_Request) (*SetParametersAtomically_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetParametersAtomically_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetParametersAtomicallyServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s SetParametersAtomicallyServiceResponseSender) SendResponse(resp *SetParametersAtomically_Response) error {
	return s.sender.SendResponse(resp)
}

type SetParametersAtomicallyServiceRequestHandler func(*humble.ServiceInfo, *SetParametersAtomically_Request, SetParametersAtomicallyServiceResponseSender)

// SetParametersAtomicallyService wraps humble.Service to provide type safe helper
// functions
type SetParametersAtomicallyService struct {
	*humble.Service
}

// NewSetParametersAtomicallyService creates and returns a new service for the
// SetParametersAtomically
func NewSetParametersAtomicallyService(node *humble.Node, name string, options *humble.ServiceOptions, handler SetParametersAtomicallyServiceRequestHandler) (*SetParametersAtomicallyService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*SetParametersAtomically_Request)
		responseSender := SetParametersAtomicallyServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetParametersAtomicallyTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetParametersAtomicallyService{service}, nil
}
