// Code generated by ros2gen. DO NOT EDIT.

package geographic_msgs_msg

import (
	"unsafe"

	std_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/std_msgs/msg"
	"github.com/okieraised/rclgo/humble"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/geo_path.h>

*/
import "C"

func init() {
	humble.RegisterMessage("geographic_msgs/GeoPath", GeoPathTypeSupport)
	humble.RegisterMessage("geographic_msgs/msg/GeoPath", GeoPathTypeSupport)
}

type GeoPath struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Poses  []GeoPoseStamped    `yaml:"poses"`
}

// NewGeoPath creates a new GeoPath with default values.
func NewGeoPath() *GeoPath {
	self := GeoPath{}
	self.SetDefaults()
	return &self
}

func (t *GeoPath) Clone() *GeoPath {
	c := &GeoPath{}
	c.Header = *t.Header.Clone()
	if t.Poses != nil {
		c.Poses = make([]GeoPoseStamped, len(t.Poses))
		CloneGeoPoseStampedSlice(c.Poses, t.Poses)
	}
	return c
}

func (t *GeoPath) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *GeoPath) SetDefaults() {
	t.Header.SetDefaults()
	t.Poses = nil
}

func (t *GeoPath) GetTypeSupport() humble.MessageTypeSupport {
	return GeoPathTypeSupport
}

// GeoPathPublisher wraps humble.Publisher to provide type safe helper
// functions
type GeoPathPublisher struct {
	*humble.Publisher
}

// NewGeoPathPublisher creates and returns a new publisher for the
// GeoPath
func NewGeoPathPublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*GeoPathPublisher, error) {
	pub, err := node.NewPublisher(topicName, GeoPathTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GeoPathPublisher{pub}, nil
}

func (p *GeoPathPublisher) Publish(msg *GeoPath) error {
	return p.Publisher.Publish(msg)
}

// GeoPathSubscription wraps humble.Subscription to provide type safe helper
// functions
type GeoPathSubscription struct {
	*humble.Subscription
}

// GeoPathSubscriptionCallback type is used to provide a subscription
// handler function for a GeoPathSubscription.
type GeoPathSubscriptionCallback func(msg *GeoPath, info *humble.MessageInfo, err error)

// NewGeoPathSubscription creates and returns a new subscription for the
// GeoPath
func NewGeoPathSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback GeoPathSubscriptionCallback) (*GeoPathSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg GeoPath
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, GeoPathTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GeoPathSubscription{sub}, nil
}

func (s *GeoPathSubscription) TakeMessage(out *GeoPath) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGeoPathSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGeoPathSlice(dst, src []GeoPath) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GeoPathTypeSupport humble.MessageTypeSupport = _GeoPathTypeSupport{}

type _GeoPathTypeSupport struct{}

func (t _GeoPathTypeSupport) New() humble.Message {
	return NewGeoPath()
}

func (t _GeoPathTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__GeoPath
	return (unsafe.Pointer)(C.geographic_msgs__msg__GeoPath__create())
}

func (t _GeoPathTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__GeoPath__destroy((*C.geographic_msgs__msg__GeoPath)(pointer_to_free))
}

func (t _GeoPathTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*GeoPath)
	mem := (*C.geographic_msgs__msg__GeoPath)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	GeoPoseStampedSequenceToC(&mem.poses, m.Poses)
}

func (t _GeoPathTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GeoPath)
	mem := (*C.geographic_msgs__msg__GeoPath)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	GeoPoseStampedSequenceToGo(&m.Poses, mem.poses)
}

func (t _GeoPathTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__GeoPath())
}

type CGeoPath = C.geographic_msgs__msg__GeoPath
type CGeoPathSequence = C.geographic_msgs__msg__GeoPath__Sequence

func GeoPathSequenceToGo(goSlice *[]GeoPath, cSlice CGeoPathSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GeoPath, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GeoPathTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func GeoPathSequenceToC(cSlice *CGeoPathSequence, goSlice []GeoPath) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__GeoPath)(C.malloc(C.sizeof_struct_geographic_msgs__msg__GeoPath * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GeoPathTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func GeoPathArrayToGo(goSlice []GeoPath, cSlice []CGeoPath) {
	for i := 0; i < len(cSlice); i++ {
		GeoPathTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func GeoPathArrayToC(cSlice []CGeoPath, goSlice []GeoPath) {
	for i := 0; i < len(goSlice); i++ {
		GeoPathTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
