// Code generated by ros2gen. DO NOT EDIT.

package rmw_dds_common_msg

import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rmw_dds_common/msg/participant_entities_info.h>

*/
import "C"

func init() {
	humble.RegisterMessage("rmw_dds_common/ParticipantEntitiesInfo", ParticipantEntitiesInfoTypeSupport)
	humble.RegisterMessage("rmw_dds_common/msg/ParticipantEntitiesInfo", ParticipantEntitiesInfoTypeSupport)
}

type ParticipantEntitiesInfo struct {
	Gid                 Gid                `yaml:"gid"`
	NodeEntitiesInfoSeq []NodeEntitiesInfo `yaml:"node_entities_info_seq"`
}

// NewParticipantEntitiesInfo creates a new ParticipantEntitiesInfo with default values.
func NewParticipantEntitiesInfo() *ParticipantEntitiesInfo {
	self := ParticipantEntitiesInfo{}
	self.SetDefaults()
	return &self
}

func (t *ParticipantEntitiesInfo) Clone() *ParticipantEntitiesInfo {
	c := &ParticipantEntitiesInfo{}
	c.Gid = *t.Gid.Clone()
	if t.NodeEntitiesInfoSeq != nil {
		c.NodeEntitiesInfoSeq = make([]NodeEntitiesInfo, len(t.NodeEntitiesInfoSeq))
		CloneNodeEntitiesInfoSlice(c.NodeEntitiesInfoSeq, t.NodeEntitiesInfoSeq)
	}
	return c
}

func (t *ParticipantEntitiesInfo) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *ParticipantEntitiesInfo) SetDefaults() {
	t.Gid.SetDefaults()
	t.NodeEntitiesInfoSeq = nil
}

func (t *ParticipantEntitiesInfo) GetTypeSupport() humble.MessageTypeSupport {
	return ParticipantEntitiesInfoTypeSupport
}

// ParticipantEntitiesInfoPublisher wraps humble.Publisher to provide type safe helper
// functions
type ParticipantEntitiesInfoPublisher struct {
	*humble.Publisher
}

// NewParticipantEntitiesInfoPublisher creates and returns a new publisher for the
// ParticipantEntitiesInfo
func NewParticipantEntitiesInfoPublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*ParticipantEntitiesInfoPublisher, error) {
	pub, err := node.NewPublisher(topicName, ParticipantEntitiesInfoTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ParticipantEntitiesInfoPublisher{pub}, nil
}

func (p *ParticipantEntitiesInfoPublisher) Publish(msg *ParticipantEntitiesInfo) error {
	return p.Publisher.Publish(msg)
}

// ParticipantEntitiesInfoSubscription wraps humble.Subscription to provide type safe helper
// functions
type ParticipantEntitiesInfoSubscription struct {
	*humble.Subscription
}

// ParticipantEntitiesInfoSubscriptionCallback type is used to provide a subscription
// handler function for a ParticipantEntitiesInfoSubscription.
type ParticipantEntitiesInfoSubscriptionCallback func(msg *ParticipantEntitiesInfo, info *humble.MessageInfo, err error)

// NewParticipantEntitiesInfoSubscription creates and returns a new subscription for the
// ParticipantEntitiesInfo
func NewParticipantEntitiesInfoSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback ParticipantEntitiesInfoSubscriptionCallback) (*ParticipantEntitiesInfoSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg ParticipantEntitiesInfo
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, ParticipantEntitiesInfoTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &ParticipantEntitiesInfoSubscription{sub}, nil
}

func (s *ParticipantEntitiesInfoSubscription) TakeMessage(out *ParticipantEntitiesInfo) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneParticipantEntitiesInfoSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneParticipantEntitiesInfoSlice(dst, src []ParticipantEntitiesInfo) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ParticipantEntitiesInfoTypeSupport humble.MessageTypeSupport = _ParticipantEntitiesInfoTypeSupport{}

type _ParticipantEntitiesInfoTypeSupport struct{}

func (t _ParticipantEntitiesInfoTypeSupport) New() humble.Message {
	return NewParticipantEntitiesInfo()
}

func (t _ParticipantEntitiesInfoTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rmw_dds_common__msg__ParticipantEntitiesInfo
	return (unsafe.Pointer)(C.rmw_dds_common__msg__ParticipantEntitiesInfo__create())
}

func (t _ParticipantEntitiesInfoTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rmw_dds_common__msg__ParticipantEntitiesInfo__destroy((*C.rmw_dds_common__msg__ParticipantEntitiesInfo)(pointer_to_free))
}

func (t _ParticipantEntitiesInfoTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*ParticipantEntitiesInfo)
	mem := (*C.rmw_dds_common__msg__ParticipantEntitiesInfo)(dst)
	GidTypeSupport.AsCStruct(unsafe.Pointer(&mem.gid), &m.Gid)
	NodeEntitiesInfoSequenceToC(&mem.node_entities_info_seq, m.NodeEntitiesInfoSeq)
}

func (t _ParticipantEntitiesInfoTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ParticipantEntitiesInfo)
	mem := (*C.rmw_dds_common__msg__ParticipantEntitiesInfo)(ros2_message_buffer)
	GidTypeSupport.AsGoStruct(&m.Gid, unsafe.Pointer(&mem.gid))
	NodeEntitiesInfoSequenceToGo(&m.NodeEntitiesInfoSeq, mem.node_entities_info_seq)
}

func (t _ParticipantEntitiesInfoTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rmw_dds_common__msg__ParticipantEntitiesInfo())
}

type CParticipantEntitiesInfo = C.rmw_dds_common__msg__ParticipantEntitiesInfo
type CParticipantEntitiesInfoSequence = C.rmw_dds_common__msg__ParticipantEntitiesInfo__Sequence

func ParticipantEntitiesInfoSequenceToGo(goSlice *[]ParticipantEntitiesInfo, cSlice CParticipantEntitiesInfoSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ParticipantEntitiesInfo, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		ParticipantEntitiesInfoTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func ParticipantEntitiesInfoSequenceToC(cSlice *CParticipantEntitiesInfoSequence, goSlice []ParticipantEntitiesInfo) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.rmw_dds_common__msg__ParticipantEntitiesInfo)(C.malloc(C.sizeof_struct_rmw_dds_common__msg__ParticipantEntitiesInfo * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		ParticipantEntitiesInfoTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func ParticipantEntitiesInfoArrayToGo(goSlice []ParticipantEntitiesInfo, cSlice []CParticipantEntitiesInfo) {
	for i := 0; i < len(cSlice); i++ {
		ParticipantEntitiesInfoTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func ParticipantEntitiesInfoArrayToC(cSlice []CParticipantEntitiesInfo, goSlice []ParticipantEntitiesInfo) {
	for i := 0; i < len(goSlice); i++ {
		ParticipantEntitiesInfoTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
