// Code generated by ros2gen. DO NOT EDIT.

package composition_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <composition_interfaces/srv/list_nodes.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("composition_interfaces/ListNodes", ListNodesTypeSupport)
	humble.RegisterService("composition_interfaces/srv/ListNodes", ListNodesTypeSupport)
}

type _ListNodesTypeSupport struct{}

func (s _ListNodesTypeSupport) Request() humble.MessageTypeSupport {
	return ListNodes_RequestTypeSupport
}

func (s _ListNodesTypeSupport) Response() humble.MessageTypeSupport {
	return ListNodes_ResponseTypeSupport
}

func (s _ListNodesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__composition_interfaces__srv__ListNodes())
}

// Modifying this variable is undefined behavior.
var ListNodesTypeSupport humble.ServiceTypeSupport = _ListNodesTypeSupport{}

// ListNodesClient wraps humble.Client to provide type safe helper
// functions
type ListNodesClient struct {
	*humble.Client
}

// NewListNodesClient creates and returns a new client for the
// ListNodes
func NewListNodesClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*ListNodesClient, error) {
	client, err := node.NewClient(serviceName, ListNodesTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &ListNodesClient{client}, nil
}

func (s *ListNodesClient) Send(ctx context.Context, req *ListNodes_Request) (*ListNodes_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*ListNodes_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type ListNodesServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s ListNodesServiceResponseSender) SendResponse(resp *ListNodes_Response) error {
	return s.sender.SendResponse(resp)
}

type ListNodesServiceRequestHandler func(*humble.ServiceInfo, *ListNodes_Request, ListNodesServiceResponseSender)

// ListNodesService wraps humble.Service to provide type safe helper
// functions
type ListNodesService struct {
	*humble.Service
}

// NewListNodesService creates and returns a new service for the
// ListNodes
func NewListNodesService(node *humble.Node, name string, options *humble.ServiceOptions, handler ListNodesServiceRequestHandler) (*ListNodesService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*ListNodes_Request)
		responseSender := ListNodesServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, ListNodesTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &ListNodesService{service}, nil
}
