// Code generated by ros2gen. DO NOT EDIT.

package diagnostic_msgs_srv

import (
	"unsafe"

	diagnostic_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/diagnostic_msgs/msg"
	"github.com/okieraised/rclgo/humble"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <diagnostic_msgs/srv/self_test.h>

*/
import "C"

func init() {
	humble.RegisterMessage("diagnostic_msgs/SelfTest_Response", SelfTest_ResponseTypeSupport)
	humble.RegisterMessage("diagnostic_msgs/srv/SelfTest_Response", SelfTest_ResponseTypeSupport)
}

type SelfTest_Response struct {
	Id     string                                 `yaml:"id"`
	Passed byte                                   `yaml:"passed"`
	Status []diagnostic_msgs_msg.DiagnosticStatus `yaml:"status"`
}

// NewSelfTest_Response creates a new SelfTest_Response with default values.
func NewSelfTest_Response() *SelfTest_Response {
	self := SelfTest_Response{}
	self.SetDefaults()
	return &self
}

func (t *SelfTest_Response) Clone() *SelfTest_Response {
	c := &SelfTest_Response{}
	c.Id = t.Id
	c.Passed = t.Passed
	if t.Status != nil {
		c.Status = make([]diagnostic_msgs_msg.DiagnosticStatus, len(t.Status))
		diagnostic_msgs_msg.CloneDiagnosticStatusSlice(c.Status, t.Status)
	}
	return c
}

func (t *SelfTest_Response) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *SelfTest_Response) SetDefaults() {
	t.Id = ""
	t.Passed = 0
	t.Status = nil
}

func (t *SelfTest_Response) GetTypeSupport() humble.MessageTypeSupport {
	return SelfTest_ResponseTypeSupport
}

// SelfTest_ResponsePublisher wraps humble.Publisher to provide type safe helper
// functions
type SelfTest_ResponsePublisher struct {
	*humble.Publisher
}

// NewSelfTest_ResponsePublisher creates and returns a new publisher for the
// SelfTest_Response
func NewSelfTest_ResponsePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*SelfTest_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, SelfTest_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SelfTest_ResponsePublisher{pub}, nil
}

func (p *SelfTest_ResponsePublisher) Publish(msg *SelfTest_Response) error {
	return p.Publisher.Publish(msg)
}

// SelfTest_ResponseSubscription wraps humble.Subscription to provide type safe helper
// functions
type SelfTest_ResponseSubscription struct {
	*humble.Subscription
}

// SelfTest_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SelfTest_ResponseSubscription.
type SelfTest_ResponseSubscriptionCallback func(msg *SelfTest_Response, info *humble.MessageInfo, err error)

// NewSelfTest_ResponseSubscription creates and returns a new subscription for the
// SelfTest_Response
func NewSelfTest_ResponseSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback SelfTest_ResponseSubscriptionCallback) (*SelfTest_ResponseSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg SelfTest_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, SelfTest_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SelfTest_ResponseSubscription{sub}, nil
}

func (s *SelfTest_ResponseSubscription) TakeMessage(out *SelfTest_Response) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSelfTest_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSelfTest_ResponseSlice(dst, src []SelfTest_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SelfTest_ResponseTypeSupport humble.MessageTypeSupport = _SelfTest_ResponseTypeSupport{}

type _SelfTest_ResponseTypeSupport struct{}

func (t _SelfTest_ResponseTypeSupport) New() humble.Message {
	return NewSelfTest_Response()
}

func (t _SelfTest_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.diagnostic_msgs__srv__SelfTest_Response
	return (unsafe.Pointer)(C.diagnostic_msgs__srv__SelfTest_Response__create())
}

func (t _SelfTest_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.diagnostic_msgs__srv__SelfTest_Response__destroy((*C.diagnostic_msgs__srv__SelfTest_Response)(pointer_to_free))
}

func (t _SelfTest_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*SelfTest_Response)
	mem := (*C.diagnostic_msgs__srv__SelfTest_Response)(dst)
	humble.StringAsCStruct(unsafe.Pointer(&mem.id), m.Id)
	mem.passed = C.uint8_t(m.Passed)
	diagnostic_msgs_msg.DiagnosticStatusSequenceToC((*diagnostic_msgs_msg.CDiagnosticStatusSequence)(unsafe.Pointer(&mem.status)), m.Status)
}

func (t _SelfTest_ResponseTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SelfTest_Response)
	mem := (*C.diagnostic_msgs__srv__SelfTest_Response)(ros2_message_buffer)
	humble.StringAsGoStruct(&m.Id, unsafe.Pointer(&mem.id))
	m.Passed = byte(mem.passed)
	diagnostic_msgs_msg.DiagnosticStatusSequenceToGo(&m.Status, *(*diagnostic_msgs_msg.CDiagnosticStatusSequence)(unsafe.Pointer(&mem.status)))
}

func (t _SelfTest_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__diagnostic_msgs__srv__SelfTest_Response())
}

type CSelfTest_Response = C.diagnostic_msgs__srv__SelfTest_Response
type CSelfTest_ResponseSequence = C.diagnostic_msgs__srv__SelfTest_Response__Sequence

func SelfTest_ResponseSequenceToGo(goSlice *[]SelfTest_Response, cSlice CSelfTest_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SelfTest_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SelfTest_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func SelfTest_ResponseSequenceToC(cSlice *CSelfTest_ResponseSequence, goSlice []SelfTest_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.diagnostic_msgs__srv__SelfTest_Response)(C.malloc(C.sizeof_struct_diagnostic_msgs__srv__SelfTest_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SelfTest_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func SelfTest_ResponseArrayToGo(goSlice []SelfTest_Response, cSlice []CSelfTest_Response) {
	for i := 0; i < len(cSlice); i++ {
		SelfTest_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func SelfTest_ResponseArrayToC(cSlice []CSelfTest_Response, goSlice []SelfTest_Response) {
	for i := 0; i < len(goSlice); i++ {
		SelfTest_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
