// Code generated by ros2gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/get_rate.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("rosbag2_interfaces/GetRate", GetRateTypeSupport)
	humble.RegisterService("rosbag2_interfaces/srv/GetRate", GetRateTypeSupport)
}

type _GetRateTypeSupport struct {}

func (s _GetRateTypeSupport) Request() humble.MessageTypeSupport {
	return GetRate_RequestTypeSupport
}

func (s _GetRateTypeSupport) Response() humble.MessageTypeSupport {
	return GetRate_ResponseTypeSupport
}

func (s _GetRateTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__GetRate())
}

// Modifying this variable is undefined behavior.
var GetRateTypeSupport humble.ServiceTypeSupport = _GetRateTypeSupport{}

// GetRateClient wraps humble.Client to provide type safe helper
// functions
type GetRateClient struct {
	*humble.Client
}

// NewGetRateClient creates and returns a new client for the
// GetRate
func NewGetRateClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*GetRateClient, error) {
	client, err := node.NewClient(serviceName, GetRateTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GetRateClient{client}, nil
}

func (s *GetRateClient) Send(ctx context.Context, req *GetRate_Request) (*GetRate_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*GetRate_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type GetRateServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s GetRateServiceResponseSender) SendResponse(resp *GetRate_Response) error {
	return s.sender.SendResponse(resp)
}

type GetRateServiceRequestHandler func(*humble.ServiceInfo, *GetRate_Request, GetRateServiceResponseSender)

// GetRateService wraps humble.Service to provide type safe helper
// functions
type GetRateService struct {
	*humble.Service
}

// NewGetRateService creates and returns a new service for the
// GetRate
func NewGetRateService(node *humble.Node, name string, options *humble.ServiceOptions, handler GetRateServiceRequestHandler) (*GetRateService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*GetRate_Request)
		responseSender := GetRateServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, GetRateTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &GetRateService{service}, nil
}