// Code generated by ros2gen. DO NOT EDIT.

package rosbag2_interfaces_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rosbag2_interfaces/srv/seek.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("rosbag2_interfaces/Seek", SeekTypeSupport)
	humble.RegisterService("rosbag2_interfaces/srv/Seek", SeekTypeSupport)
}

type _SeekTypeSupport struct{}

func (s _SeekTypeSupport) Request() humble.MessageTypeSupport {
	return Seek_RequestTypeSupport
}

func (s _SeekTypeSupport) Response() humble.MessageTypeSupport {
	return Seek_ResponseTypeSupport
}

func (s _SeekTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rosbag2_interfaces__srv__Seek())
}

// Modifying this variable is undefined behavior.
var SeekTypeSupport humble.ServiceTypeSupport = _SeekTypeSupport{}

// SeekClient wraps humble.Client to provide type safe helper
// functions
type SeekClient struct {
	*humble.Client
}

// NewSeekClient creates and returns a new client for the
// Seek
func NewSeekClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*SeekClient, error) {
	client, err := node.NewClient(serviceName, SeekTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SeekClient{client}, nil
}

func (s *SeekClient) Send(ctx context.Context, req *Seek_Request) (*Seek_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*Seek_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SeekServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s SeekServiceResponseSender) SendResponse(resp *Seek_Response) error {
	return s.sender.SendResponse(resp)
}

type SeekServiceRequestHandler func(*humble.ServiceInfo, *Seek_Request, SeekServiceResponseSender)

// SeekService wraps humble.Service to provide type safe helper
// functions
type SeekService struct {
	*humble.Service
}

// NewSeekService creates and returns a new service for the
// Seek
func NewSeekService(node *humble.Node, name string, options *humble.ServiceOptions, handler SeekServiceRequestHandler) (*SeekService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*Seek_Request)
		responseSender := SeekServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SeekTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SeekService{service}, nil
}
