// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/dynamic_follower.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("as2_msgs/DynamicFollower", DynamicFollowerTypeSupport)
	humble.RegisterService("as2_msgs/srv/DynamicFollower", DynamicFollowerTypeSupport)
}

type _DynamicFollowerTypeSupport struct{}

func (s _DynamicFollowerTypeSupport) Request() humble.MessageTypeSupport {
	return DynamicFollower_RequestTypeSupport
}

func (s _DynamicFollowerTypeSupport) Response() humble.MessageTypeSupport {
	return DynamicFollower_ResponseTypeSupport
}

func (s _DynamicFollowerTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__DynamicFollower())
}

// Modifying this variable is undefined behavior.
var DynamicFollowerTypeSupport humble.ServiceTypeSupport = _DynamicFollowerTypeSupport{}

// DynamicFollowerClient wraps humble.Client to provide type safe helper
// functions
type DynamicFollowerClient struct {
	*humble.Client
}

// NewDynamicFollowerClient creates and returns a new client for the
// DynamicFollower
func NewDynamicFollowerClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*DynamicFollowerClient, error) {
	client, err := node.NewClient(serviceName, DynamicFollowerTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &DynamicFollowerClient{client}, nil
}

func (s *DynamicFollowerClient) Send(ctx context.Context, req *DynamicFollower_Request) (*DynamicFollower_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*DynamicFollower_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type DynamicFollowerServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s DynamicFollowerServiceResponseSender) SendResponse(resp *DynamicFollower_Response) error {
	return s.sender.SendResponse(resp)
}

type DynamicFollowerServiceRequestHandler func(*humble.ServiceInfo, *DynamicFollower_Request, DynamicFollowerServiceResponseSender)

// DynamicFollowerService wraps humble.Service to provide type safe helper
// functions
type DynamicFollowerService struct {
	*humble.Service
}

// NewDynamicFollowerService creates and returns a new service for the
// DynamicFollower
func NewDynamicFollowerService(node *humble.Node, name string, options *humble.ServiceOptions, handler DynamicFollowerServiceRequestHandler) (*DynamicFollowerService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*DynamicFollower_Request)
		responseSender := DynamicFollowerServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, DynamicFollowerTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &DynamicFollowerService{service}, nil
}
