// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	nav_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/nav_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <as2_msgs/srv/geopath_to_path.h>

*/
import "C"

func init() {
	humble.RegisterMessage("as2_msgs/GeopathToPath_Response", GeopathToPath_ResponseTypeSupport)
	humble.RegisterMessage("as2_msgs/srv/GeopathToPath_Response", GeopathToPath_ResponseTypeSupport)
}

type GeopathToPath_Response struct {
	Success bool `yaml:"success"`// whether the origin has been set or not
	Path nav_msgs_msg.Path `yaml:"path"`// Path in meters
}

// NewGeopathToPath_Response creates a new GeopathToPath_Response with default values.
func NewGeopathToPath_Response() *GeopathToPath_Response {
	self := GeopathToPath_Response{}
	self.SetDefaults()
	return &self
}

func (t *GeopathToPath_Response) Clone() *GeopathToPath_Response {
	c := &GeopathToPath_Response{}
	c.Success = t.Success
	c.Path = *t.Path.Clone()
	return c
}

func (t *GeopathToPath_Response) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *GeopathToPath_Response) SetDefaults() {
	t.Success = false
	t.Path.SetDefaults()
}

func (t *GeopathToPath_Response) GetTypeSupport() humble.MessageTypeSupport {
	return GeopathToPath_ResponseTypeSupport
}

// GeopathToPath_ResponsePublisher wraps humble.Publisher to provide type safe helper
// functions
type GeopathToPath_ResponsePublisher struct {
	*humble.Publisher
}

// NewGeopathToPath_ResponsePublisher creates and returns a new publisher for the
// GeopathToPath_Response
func NewGeopathToPath_ResponsePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*GeopathToPath_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, GeopathToPath_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &GeopathToPath_ResponsePublisher{pub}, nil
}

func (p *GeopathToPath_ResponsePublisher) Publish(msg *GeopathToPath_Response) error {
	return p.Publisher.Publish(msg)
}

// GeopathToPath_ResponseSubscription wraps humble.Subscription to provide type safe helper
// functions
type GeopathToPath_ResponseSubscription struct {
	*humble.Subscription
}

// GeopathToPath_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a GeopathToPath_ResponseSubscription.
type GeopathToPath_ResponseSubscriptionCallback func(msg *GeopathToPath_Response, info *humble.MessageInfo, err error)

// NewGeopathToPath_ResponseSubscription creates and returns a new subscription for the
// GeopathToPath_Response
func NewGeopathToPath_ResponseSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback GeopathToPath_ResponseSubscriptionCallback) (*GeopathToPath_ResponseSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg GeopathToPath_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, GeopathToPath_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &GeopathToPath_ResponseSubscription{sub}, nil
}

func (s *GeopathToPath_ResponseSubscription) TakeMessage(out *GeopathToPath_Response) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneGeopathToPath_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGeopathToPath_ResponseSlice(dst, src []GeopathToPath_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GeopathToPath_ResponseTypeSupport humble.MessageTypeSupport = _GeopathToPath_ResponseTypeSupport{}

type _GeopathToPath_ResponseTypeSupport struct{}

func (t _GeopathToPath_ResponseTypeSupport) New() humble.Message {
	return NewGeopathToPath_Response()
}

func (t _GeopathToPath_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.as2_msgs__srv__GeopathToPath_Response
	return (unsafe.Pointer)(C.as2_msgs__srv__GeopathToPath_Response__create())
}

func (t _GeopathToPath_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.as2_msgs__srv__GeopathToPath_Response__destroy((*C.as2_msgs__srv__GeopathToPath_Response)(pointer_to_free))
}

func (t _GeopathToPath_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*GeopathToPath_Response)
	mem := (*C.as2_msgs__srv__GeopathToPath_Response)(dst)
	mem.success = C.bool(m.Success)
	nav_msgs_msg.PathTypeSupport.AsCStruct(unsafe.Pointer(&mem.path), &m.Path)
}

func (t _GeopathToPath_ResponseTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GeopathToPath_Response)
	mem := (*C.as2_msgs__srv__GeopathToPath_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	nav_msgs_msg.PathTypeSupport.AsGoStruct(&m.Path, unsafe.Pointer(&mem.path))
}

func (t _GeopathToPath_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__as2_msgs__srv__GeopathToPath_Response())
}

type CGeopathToPath_Response = C.as2_msgs__srv__GeopathToPath_Response
type CGeopathToPath_ResponseSequence = C.as2_msgs__srv__GeopathToPath_Response__Sequence

func GeopathToPath_ResponseSequenceToGo(goSlice *[]GeopathToPath_Response, cSlice CGeopathToPath_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GeopathToPath_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		GeopathToPath_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func GeopathToPath_ResponseSequenceToC(cSlice *CGeopathToPath_ResponseSequence, goSlice []GeopathToPath_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.as2_msgs__srv__GeopathToPath_Response)(C.malloc(C.sizeof_struct_as2_msgs__srv__GeopathToPath_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		GeopathToPath_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func GeopathToPath_ResponseArrayToGo(goSlice []GeopathToPath_Response, cSlice []CGeopathToPath_Response) {
	for i := 0; i < len(cSlice); i++ {
		GeopathToPath_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func GeopathToPath_ResponseArrayToC(cSlice []CGeopathToPath_Response, goSlice []GeopathToPath_Response) {
	for i := 0; i < len(goSlice); i++ {
		GeopathToPath_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
