// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/package_pick_up.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("as2_msgs/PackagePickUp", PackagePickUpTypeSupport)
	humble.RegisterService("as2_msgs/srv/PackagePickUp", PackagePickUpTypeSupport)
}

type _PackagePickUpTypeSupport struct{}

func (s _PackagePickUpTypeSupport) Request() humble.MessageTypeSupport {
	return PackagePickUp_RequestTypeSupport
}

func (s _PackagePickUpTypeSupport) Response() humble.MessageTypeSupport {
	return PackagePickUp_ResponseTypeSupport
}

func (s _PackagePickUpTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__PackagePickUp())
}

// Modifying this variable is undefined behavior.
var PackagePickUpTypeSupport humble.ServiceTypeSupport = _PackagePickUpTypeSupport{}

// PackagePickUpClient wraps humble.Client to provide type safe helper
// functions
type PackagePickUpClient struct {
	*humble.Client
}

// NewPackagePickUpClient creates and returns a new client for the
// PackagePickUp
func NewPackagePickUpClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*PackagePickUpClient, error) {
	client, err := node.NewClient(serviceName, PackagePickUpTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PackagePickUpClient{client}, nil
}

func (s *PackagePickUpClient) Send(ctx context.Context, req *PackagePickUp_Request) (*PackagePickUp_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*PackagePickUp_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type PackagePickUpServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s PackagePickUpServiceResponseSender) SendResponse(resp *PackagePickUp_Response) error {
	return s.sender.SendResponse(resp)
}

type PackagePickUpServiceRequestHandler func(*humble.ServiceInfo, *PackagePickUp_Request, PackagePickUpServiceResponseSender)

// PackagePickUpService wraps humble.Service to provide type safe helper
// functions
type PackagePickUpService struct {
	*humble.Service
}

// NewPackagePickUpService creates and returns a new service for the
// PackagePickUp
func NewPackagePickUpService(node *humble.Node, name string, options *humble.ServiceOptions, handler PackagePickUpServiceRequestHandler) (*PackagePickUpService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*PackagePickUp_Request)
		responseSender := PackagePickUpServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, PackagePickUpTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &PackagePickUpService{service}, nil
}
