// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <as2_msgs/srv/package_un_pick.h>

*/
import "C"

func init() {
	humble.RegisterMessage("as2_msgs/PackageUnPick_Response", PackageUnPick_ResponseTypeSupport)
	humble.RegisterMessage("as2_msgs/srv/PackageUnPick_Response", PackageUnPick_ResponseTypeSupport)
}

type PackageUnPick_Response struct {
	Success bool `yaml:"success"`// whether it could be started or not
}

// NewPackageUnPick_Response creates a new PackageUnPick_Response with default values.
func NewPackageUnPick_Response() *PackageUnPick_Response {
	self := PackageUnPick_Response{}
	self.SetDefaults()
	return &self
}

func (t *PackageUnPick_Response) Clone() *PackageUnPick_Response {
	c := &PackageUnPick_Response{}
	c.Success = t.Success
	return c
}

func (t *PackageUnPick_Response) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *PackageUnPick_Response) SetDefaults() {
	t.Success = false
}

func (t *PackageUnPick_Response) GetTypeSupport() humble.MessageTypeSupport {
	return PackageUnPick_ResponseTypeSupport
}

// PackageUnPick_ResponsePublisher wraps humble.Publisher to provide type safe helper
// functions
type PackageUnPick_ResponsePublisher struct {
	*humble.Publisher
}

// NewPackageUnPick_ResponsePublisher creates and returns a new publisher for the
// PackageUnPick_Response
func NewPackageUnPick_ResponsePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*PackageUnPick_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, PackageUnPick_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &PackageUnPick_ResponsePublisher{pub}, nil
}

func (p *PackageUnPick_ResponsePublisher) Publish(msg *PackageUnPick_Response) error {
	return p.Publisher.Publish(msg)
}

// PackageUnPick_ResponseSubscription wraps humble.Subscription to provide type safe helper
// functions
type PackageUnPick_ResponseSubscription struct {
	*humble.Subscription
}

// PackageUnPick_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a PackageUnPick_ResponseSubscription.
type PackageUnPick_ResponseSubscriptionCallback func(msg *PackageUnPick_Response, info *humble.MessageInfo, err error)

// NewPackageUnPick_ResponseSubscription creates and returns a new subscription for the
// PackageUnPick_Response
func NewPackageUnPick_ResponseSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback PackageUnPick_ResponseSubscriptionCallback) (*PackageUnPick_ResponseSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg PackageUnPick_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, PackageUnPick_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &PackageUnPick_ResponseSubscription{sub}, nil
}

func (s *PackageUnPick_ResponseSubscription) TakeMessage(out *PackageUnPick_Response) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// ClonePackageUnPick_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePackageUnPick_ResponseSlice(dst, src []PackageUnPick_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var PackageUnPick_ResponseTypeSupport humble.MessageTypeSupport = _PackageUnPick_ResponseTypeSupport{}

type _PackageUnPick_ResponseTypeSupport struct{}

func (t _PackageUnPick_ResponseTypeSupport) New() humble.Message {
	return NewPackageUnPick_Response()
}

func (t _PackageUnPick_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.as2_msgs__srv__PackageUnPick_Response
	return (unsafe.Pointer)(C.as2_msgs__srv__PackageUnPick_Response__create())
}

func (t _PackageUnPick_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.as2_msgs__srv__PackageUnPick_Response__destroy((*C.as2_msgs__srv__PackageUnPick_Response)(pointer_to_free))
}

func (t _PackageUnPick_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*PackageUnPick_Response)
	mem := (*C.as2_msgs__srv__PackageUnPick_Response)(dst)
	mem.success = C.bool(m.Success)
}

func (t _PackageUnPick_ResponseTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*PackageUnPick_Response)
	mem := (*C.as2_msgs__srv__PackageUnPick_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
}

func (t _PackageUnPick_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__as2_msgs__srv__PackageUnPick_Response())
}

type CPackageUnPick_Response = C.as2_msgs__srv__PackageUnPick_Response
type CPackageUnPick_ResponseSequence = C.as2_msgs__srv__PackageUnPick_Response__Sequence

func PackageUnPick_ResponseSequenceToGo(goSlice *[]PackageUnPick_Response, cSlice CPackageUnPick_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]PackageUnPick_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		PackageUnPick_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func PackageUnPick_ResponseSequenceToC(cSlice *CPackageUnPick_ResponseSequence, goSlice []PackageUnPick_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.as2_msgs__srv__PackageUnPick_Response)(C.malloc(C.sizeof_struct_as2_msgs__srv__PackageUnPick_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		PackageUnPick_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func PackageUnPick_ResponseArrayToGo(goSlice []PackageUnPick_Response, cSlice []CPackageUnPick_Response) {
	for i := 0; i < len(cSlice); i++ {
		PackageUnPick_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func PackageUnPick_ResponseArrayToC(cSlice []CPackageUnPick_Response, goSlice []PackageUnPick_Response) {
	for i := 0; i < len(goSlice); i++ {
		PackageUnPick_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
