// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_srv

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/srv/set_origin.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("as2_msgs/SetOrigin", SetOriginTypeSupport)
	humble.RegisterService("as2_msgs/srv/SetOrigin", SetOriginTypeSupport)
}

type _SetOriginTypeSupport struct {}

func (s _SetOriginTypeSupport) Request() humble.MessageTypeSupport {
	return SetOrigin_RequestTypeSupport
}

func (s _SetOriginTypeSupport) Response() humble.MessageTypeSupport {
	return SetOrigin_ResponseTypeSupport
}

func (s _SetOriginTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__srv__SetOrigin())
}

// Modifying this variable is undefined behavior.
var SetOriginTypeSupport humble.ServiceTypeSupport = _SetOriginTypeSupport{}

// SetOriginClient wraps humble.Client to provide type safe helper
// functions
type SetOriginClient struct {
	*humble.Client
}

// NewSetOriginClient creates and returns a new client for the
// SetOrigin
func NewSetOriginClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*SetOriginClient, error) {
	client, err := node.NewClient(serviceName, SetOriginTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetOriginClient{client}, nil
}

func (s *SetOriginClient) Send(ctx context.Context, req *SetOrigin_Request) (*SetOrigin_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetOrigin_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetOriginServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s SetOriginServiceResponseSender) SendResponse(resp *SetOrigin_Response) error {
	return s.sender.SendResponse(resp)
}

type SetOriginServiceRequestHandler func(*humble.ServiceInfo, *SetOrigin_Request, SetOriginServiceResponseSender)

// SetOriginService wraps humble.Service to provide type safe helper
// functions
type SetOriginService struct {
	*humble.Service
}

// NewSetOriginService creates and returns a new service for the
// SetOrigin
func NewSetOriginService(node *humble.Node, name string, options *humble.ServiceOptions, handler SetOriginServiceRequestHandler) (*SetOriginService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*SetOrigin_Request)
		responseSender := SetOriginServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetOriginTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetOriginService{service}, nil
}