// Code generated by ros2gen. DO NOT EDIT.

package unitree_hg_msg
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <unitree_hg/msg/bms_state.h>

*/
import "C"

func init() {
	humble.RegisterMessage("unitree_hg/BmsState", BmsStateTypeSupport)
	humble.RegisterMessage("unitree_hg/msg/BmsState", BmsStateTypeSupport)
}

type BmsState struct {
	VersionHigh uint8 `yaml:"version_high"`
	VersionLow uint8 `yaml:"version_low"`
	Fn uint8 `yaml:"fn"`
	CellVol [40]uint16 `yaml:"cell_vol"`
	Bmsvoltage [3]uint32 `yaml:"bmsvoltage"`
	Current int32 `yaml:"current"`
	Soc uint8 `yaml:"soc"`
	Soh uint8 `yaml:"soh"`
	Temperature [12]int16 `yaml:"temperature"`
	Cycle uint16 `yaml:"cycle"`
	ManufacturerDate uint16 `yaml:"manufacturer_date"`
	Bmsstate [5]uint32 `yaml:"bmsstate"`
	Reserve [3]uint32 `yaml:"reserve"`
}

// NewBmsState creates a new BmsState with default values.
func NewBmsState() *BmsState {
	self := BmsState{}
	self.SetDefaults()
	return &self
}

func (t *BmsState) Clone() *BmsState {
	c := &BmsState{}
	c.VersionHigh = t.VersionHigh
	c.VersionLow = t.VersionLow
	c.Fn = t.Fn
	c.CellVol = t.CellVol
	c.Bmsvoltage = t.Bmsvoltage
	c.Current = t.Current
	c.Soc = t.Soc
	c.Soh = t.Soh
	c.Temperature = t.Temperature
	c.Cycle = t.Cycle
	c.ManufacturerDate = t.ManufacturerDate
	c.Bmsstate = t.Bmsstate
	c.Reserve = t.Reserve
	return c
}

func (t *BmsState) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *BmsState) SetDefaults() {
	t.VersionHigh = 0
	t.VersionLow = 0
	t.Fn = 0
	t.CellVol = [40]uint16{}
	t.Bmsvoltage = [3]uint32{}
	t.Current = 0
	t.Soc = 0
	t.Soh = 0
	t.Temperature = [12]int16{}
	t.Cycle = 0
	t.ManufacturerDate = 0
	t.Bmsstate = [5]uint32{}
	t.Reserve = [3]uint32{}
}

func (t *BmsState) GetTypeSupport() humble.MessageTypeSupport {
	return BmsStateTypeSupport
}

// BmsStatePublisher wraps humble.Publisher to provide type safe helper
// functions
type BmsStatePublisher struct {
	*humble.Publisher
}

// NewBmsStatePublisher creates and returns a new publisher for the
// BmsState
func NewBmsStatePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*BmsStatePublisher, error) {
	pub, err := node.NewPublisher(topicName, BmsStateTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &BmsStatePublisher{pub}, nil
}

func (p *BmsStatePublisher) Publish(msg *BmsState) error {
	return p.Publisher.Publish(msg)
}

// BmsStateSubscription wraps humble.Subscription to provide type safe helper
// functions
type BmsStateSubscription struct {
	*humble.Subscription
}

// BmsStateSubscriptionCallback type is used to provide a subscription
// handler function for a BmsStateSubscription.
type BmsStateSubscriptionCallback func(msg *BmsState, info *humble.MessageInfo, err error)

// NewBmsStateSubscription creates and returns a new subscription for the
// BmsState
func NewBmsStateSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback BmsStateSubscriptionCallback) (*BmsStateSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg BmsState
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, BmsStateTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &BmsStateSubscription{sub}, nil
}

func (s *BmsStateSubscription) TakeMessage(out *BmsState) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneBmsStateSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneBmsStateSlice(dst, src []BmsState) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var BmsStateTypeSupport humble.MessageTypeSupport = _BmsStateTypeSupport{}

type _BmsStateTypeSupport struct{}

func (t _BmsStateTypeSupport) New() humble.Message {
	return NewBmsState()
}

func (t _BmsStateTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.unitree_hg__msg__BmsState
	return (unsafe.Pointer)(C.unitree_hg__msg__BmsState__create())
}

func (t _BmsStateTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.unitree_hg__msg__BmsState__destroy((*C.unitree_hg__msg__BmsState)(pointer_to_free))
}

func (t _BmsStateTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*BmsState)
	mem := (*C.unitree_hg__msg__BmsState)(dst)
	mem.version_high = C.uint8_t(m.VersionHigh)
	mem.version_low = C.uint8_t(m.VersionLow)
	mem.fn = C.uint8_t(m.Fn)
	cSlice_cell_vol := mem.cell_vol[:]
	humble.Uint16ArrayToC(*(*[]humble.CUint16)(unsafe.Pointer(&cSlice_cell_vol)), m.CellVol[:])
	cSlice_bmsvoltage := mem.bmsvoltage[:]
	humble.Uint32ArrayToC(*(*[]humble.CUint32)(unsafe.Pointer(&cSlice_bmsvoltage)), m.Bmsvoltage[:])
	mem.current = C.int32_t(m.Current)
	mem.soc = C.uint8_t(m.Soc)
	mem.soh = C.uint8_t(m.Soh)
	cSlice_temperature := mem.temperature[:]
	humble.Int16ArrayToC(*(*[]humble.CInt16)(unsafe.Pointer(&cSlice_temperature)), m.Temperature[:])
	mem.cycle = C.uint16_t(m.Cycle)
	mem.manufacturer_date = C.uint16_t(m.ManufacturerDate)
	cSlice_bmsstate := mem.bmsstate[:]
	humble.Uint32ArrayToC(*(*[]humble.CUint32)(unsafe.Pointer(&cSlice_bmsstate)), m.Bmsstate[:])
	cSlice_reserve := mem.reserve[:]
	humble.Uint32ArrayToC(*(*[]humble.CUint32)(unsafe.Pointer(&cSlice_reserve)), m.Reserve[:])
}

func (t _BmsStateTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*BmsState)
	mem := (*C.unitree_hg__msg__BmsState)(ros2_message_buffer)
	m.VersionHigh = uint8(mem.version_high)
	m.VersionLow = uint8(mem.version_low)
	m.Fn = uint8(mem.fn)
	cSlice_cell_vol := mem.cell_vol[:]
	humble.Uint16ArrayToGo(m.CellVol[:], *(*[]humble.CUint16)(unsafe.Pointer(&cSlice_cell_vol)))
	cSlice_bmsvoltage := mem.bmsvoltage[:]
	humble.Uint32ArrayToGo(m.Bmsvoltage[:], *(*[]humble.CUint32)(unsafe.Pointer(&cSlice_bmsvoltage)))
	m.Current = int32(mem.current)
	m.Soc = uint8(mem.soc)
	m.Soh = uint8(mem.soh)
	cSlice_temperature := mem.temperature[:]
	humble.Int16ArrayToGo(m.Temperature[:], *(*[]humble.CInt16)(unsafe.Pointer(&cSlice_temperature)))
	m.Cycle = uint16(mem.cycle)
	m.ManufacturerDate = uint16(mem.manufacturer_date)
	cSlice_bmsstate := mem.bmsstate[:]
	humble.Uint32ArrayToGo(m.Bmsstate[:], *(*[]humble.CUint32)(unsafe.Pointer(&cSlice_bmsstate)))
	cSlice_reserve := mem.reserve[:]
	humble.Uint32ArrayToGo(m.Reserve[:], *(*[]humble.CUint32)(unsafe.Pointer(&cSlice_reserve)))
}

func (t _BmsStateTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__unitree_hg__msg__BmsState())
}

type CBmsState = C.unitree_hg__msg__BmsState
type CBmsStateSequence = C.unitree_hg__msg__BmsState__Sequence

func BmsStateSequenceToGo(goSlice *[]BmsState, cSlice CBmsStateSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]BmsState, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		BmsStateTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func BmsStateSequenceToC(cSlice *CBmsStateSequence, goSlice []BmsState) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.unitree_hg__msg__BmsState)(C.malloc(C.sizeof_struct_unitree_hg__msg__BmsState * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		BmsStateTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func BmsStateArrayToGo(goSlice []BmsState, cSlice []CBmsState) {
	for i := 0; i < len(cSlice); i++ {
		BmsStateTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func BmsStateArrayToC(cSlice []CBmsState, goSlice []BmsState) {
	for i := 0; i < len(goSlice); i++ {
		BmsStateTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
