// Code generated by ros2gen. DO NOT EDIT.

package sensor_msgs_msg
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	std_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/std_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <sensor_msgs/msg/illuminance.h>

*/
import "C"

func init() {
	humble.RegisterMessage("sensor_msgs/Illuminance", IlluminanceTypeSupport)
	humble.RegisterMessage("sensor_msgs/msg/Illuminance", IlluminanceTypeSupport)
}

type Illuminance struct {
	Header std_msgs_msg.Header `yaml:"header"`// timestamp is the time the illuminance was measured
	Illuminance float64 `yaml:"illuminance"`// Measurement of the Photometric Illuminance in Lux.
	Variance float64 `yaml:"variance"`// 0 is interpreted as variance unknown
}

// NewIlluminance creates a new Illuminance with default values.
func NewIlluminance() *Illuminance {
	self := Illuminance{}
	self.SetDefaults()
	return &self
}

func (t *Illuminance) Clone() *Illuminance {
	c := &Illuminance{}
	c.Header = *t.Header.Clone()
	c.Illuminance = t.Illuminance
	c.Variance = t.Variance
	return c
}

func (t *Illuminance) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *Illuminance) SetDefaults() {
	t.Header.SetDefaults()
	t.Illuminance = 0
	t.Variance = 0
}

func (t *Illuminance) GetTypeSupport() humble.MessageTypeSupport {
	return IlluminanceTypeSupport
}

// IlluminancePublisher wraps humble.Publisher to provide type safe helper
// functions
type IlluminancePublisher struct {
	*humble.Publisher
}

// NewIlluminancePublisher creates and returns a new publisher for the
// Illuminance
func NewIlluminancePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*IlluminancePublisher, error) {
	pub, err := node.NewPublisher(topicName, IlluminanceTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &IlluminancePublisher{pub}, nil
}

func (p *IlluminancePublisher) Publish(msg *Illuminance) error {
	return p.Publisher.Publish(msg)
}

// IlluminanceSubscription wraps humble.Subscription to provide type safe helper
// functions
type IlluminanceSubscription struct {
	*humble.Subscription
}

// IlluminanceSubscriptionCallback type is used to provide a subscription
// handler function for a IlluminanceSubscription.
type IlluminanceSubscriptionCallback func(msg *Illuminance, info *humble.MessageInfo, err error)

// NewIlluminanceSubscription creates and returns a new subscription for the
// Illuminance
func NewIlluminanceSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback IlluminanceSubscriptionCallback) (*IlluminanceSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg Illuminance
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, IlluminanceTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &IlluminanceSubscription{sub}, nil
}

func (s *IlluminanceSubscription) TakeMessage(out *Illuminance) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneIlluminanceSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneIlluminanceSlice(dst, src []Illuminance) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var IlluminanceTypeSupport humble.MessageTypeSupport = _IlluminanceTypeSupport{}

type _IlluminanceTypeSupport struct{}

func (t _IlluminanceTypeSupport) New() humble.Message {
	return NewIlluminance()
}

func (t _IlluminanceTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.sensor_msgs__msg__Illuminance
	return (unsafe.Pointer)(C.sensor_msgs__msg__Illuminance__create())
}

func (t _IlluminanceTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.sensor_msgs__msg__Illuminance__destroy((*C.sensor_msgs__msg__Illuminance)(pointer_to_free))
}

func (t _IlluminanceTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*Illuminance)
	mem := (*C.sensor_msgs__msg__Illuminance)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	mem.illuminance = C.double(m.Illuminance)
	mem.variance = C.double(m.Variance)
}

func (t _IlluminanceTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Illuminance)
	mem := (*C.sensor_msgs__msg__Illuminance)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	m.Illuminance = float64(mem.illuminance)
	m.Variance = float64(mem.variance)
}

func (t _IlluminanceTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__Illuminance())
}

type CIlluminance = C.sensor_msgs__msg__Illuminance
type CIlluminanceSequence = C.sensor_msgs__msg__Illuminance__Sequence

func IlluminanceSequenceToGo(goSlice *[]Illuminance, cSlice CIlluminanceSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Illuminance, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		IlluminanceTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func IlluminanceSequenceToC(cSlice *CIlluminanceSequence, goSlice []Illuminance) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.sensor_msgs__msg__Illuminance)(C.malloc(C.sizeof_struct_sensor_msgs__msg__Illuminance * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		IlluminanceTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func IlluminanceArrayToGo(goSlice []Illuminance, cSlice []CIlluminance) {
	for i := 0; i < len(cSlice); i++ {
		IlluminanceTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func IlluminanceArrayToC(cSlice []CIlluminance, goSlice []Illuminance) {
	for i := 0; i < len(goSlice); i++ {
		IlluminanceTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
