// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <as2_msgs/action/follow_path.h>

*/
import "C"

func init() {
	humble.RegisterMessage("as2_msgs/FollowPath_GetResult_Response", FollowPath_GetResult_ResponseTypeSupport)
	humble.RegisterMessage("as2_msgs/action/FollowPath_GetResult_Response", FollowPath_GetResult_ResponseTypeSupport)
}

type FollowPath_GetResult_Response struct {
	Status int8 `yaml:"status"`
	Result FollowPath_Result `yaml:"result"`
}

// NewFollowPath_GetResult_Response creates a new FollowPath_GetResult_Response with default values.
func NewFollowPath_GetResult_Response() *FollowPath_GetResult_Response {
	self := FollowPath_GetResult_Response{}
	self.SetDefaults()
	return &self
}

func (t *FollowPath_GetResult_Response) Clone() *FollowPath_GetResult_Response {
	c := &FollowPath_GetResult_Response{}
	c.Status = t.Status
	c.Result = *t.Result.Clone()
	return c
}

func (t *FollowPath_GetResult_Response) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *FollowPath_GetResult_Response) SetDefaults() {
	t.Status = 0
	t.Result.SetDefaults()
}

func (t *FollowPath_GetResult_Response) GetTypeSupport() humble.MessageTypeSupport {
	return FollowPath_GetResult_ResponseTypeSupport
}

// FollowPath_GetResult_ResponsePublisher wraps humble.Publisher to provide type safe helper
// functions
type FollowPath_GetResult_ResponsePublisher struct {
	*humble.Publisher
}

// NewFollowPath_GetResult_ResponsePublisher creates and returns a new publisher for the
// FollowPath_GetResult_Response
func NewFollowPath_GetResult_ResponsePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*FollowPath_GetResult_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, FollowPath_GetResult_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowPath_GetResult_ResponsePublisher{pub}, nil
}

func (p *FollowPath_GetResult_ResponsePublisher) Publish(msg *FollowPath_GetResult_Response) error {
	return p.Publisher.Publish(msg)
}

// FollowPath_GetResult_ResponseSubscription wraps humble.Subscription to provide type safe helper
// functions
type FollowPath_GetResult_ResponseSubscription struct {
	*humble.Subscription
}

// FollowPath_GetResult_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a FollowPath_GetResult_ResponseSubscription.
type FollowPath_GetResult_ResponseSubscriptionCallback func(msg *FollowPath_GetResult_Response, info *humble.MessageInfo, err error)

// NewFollowPath_GetResult_ResponseSubscription creates and returns a new subscription for the
// FollowPath_GetResult_Response
func NewFollowPath_GetResult_ResponseSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback FollowPath_GetResult_ResponseSubscriptionCallback) (*FollowPath_GetResult_ResponseSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg FollowPath_GetResult_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, FollowPath_GetResult_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FollowPath_GetResult_ResponseSubscription{sub}, nil
}

func (s *FollowPath_GetResult_ResponseSubscription) TakeMessage(out *FollowPath_GetResult_Response) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFollowPath_GetResult_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFollowPath_GetResult_ResponseSlice(dst, src []FollowPath_GetResult_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FollowPath_GetResult_ResponseTypeSupport humble.MessageTypeSupport = _FollowPath_GetResult_ResponseTypeSupport{}

type _FollowPath_GetResult_ResponseTypeSupport struct{}

func (t _FollowPath_GetResult_ResponseTypeSupport) New() humble.Message {
	return NewFollowPath_GetResult_Response()
}

func (t _FollowPath_GetResult_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.as2_msgs__action__FollowPath_GetResult_Response
	return (unsafe.Pointer)(C.as2_msgs__action__FollowPath_GetResult_Response__create())
}

func (t _FollowPath_GetResult_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.as2_msgs__action__FollowPath_GetResult_Response__destroy((*C.as2_msgs__action__FollowPath_GetResult_Response)(pointer_to_free))
}

func (t _FollowPath_GetResult_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*FollowPath_GetResult_Response)
	mem := (*C.as2_msgs__action__FollowPath_GetResult_Response)(dst)
	mem.status = C.int8_t(m.Status)
	FollowPath_ResultTypeSupport.AsCStruct(unsafe.Pointer(&mem.result), &m.Result)
}

func (t _FollowPath_GetResult_ResponseTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FollowPath_GetResult_Response)
	mem := (*C.as2_msgs__action__FollowPath_GetResult_Response)(ros2_message_buffer)
	m.Status = int8(mem.status)
	FollowPath_ResultTypeSupport.AsGoStruct(&m.Result, unsafe.Pointer(&mem.result))
}

func (t _FollowPath_GetResult_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__as2_msgs__action__FollowPath_GetResult_Response())
}

type CFollowPath_GetResult_Response = C.as2_msgs__action__FollowPath_GetResult_Response
type CFollowPath_GetResult_ResponseSequence = C.as2_msgs__action__FollowPath_GetResult_Response__Sequence

func FollowPath_GetResult_ResponseSequenceToGo(goSlice *[]FollowPath_GetResult_Response, cSlice CFollowPath_GetResult_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FollowPath_GetResult_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FollowPath_GetResult_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func FollowPath_GetResult_ResponseSequenceToC(cSlice *CFollowPath_GetResult_ResponseSequence, goSlice []FollowPath_GetResult_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.as2_msgs__action__FollowPath_GetResult_Response)(C.malloc(C.sizeof_struct_as2_msgs__action__FollowPath_GetResult_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FollowPath_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func FollowPath_GetResult_ResponseArrayToGo(goSlice []FollowPath_GetResult_Response, cSlice []CFollowPath_GetResult_Response) {
	for i := 0; i < len(cSlice); i++ {
		FollowPath_GetResult_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func FollowPath_GetResult_ResponseArrayToC(cSlice []CFollowPath_GetResult_Response, goSlice []FollowPath_GetResult_Response) {
	for i := 0; i < len(goSlice); i++ {
		FollowPath_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
