// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

import (
	"unsafe"

	unique_identifier_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/unique_identifier_msgs/msg"
	"github.com/okieraised/rclgo/humble"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <as2_msgs/action/follow_path.h>

*/
import "C"

func init() {
	humble.RegisterMessage("as2_msgs/FollowPath_FeedbackMessage", FollowPath_FeedbackMessageTypeSupport)
	humble.RegisterMessage("as2_msgs/action/FollowPath_FeedbackMessage", FollowPath_FeedbackMessageTypeSupport)
}

type FollowPath_FeedbackMessage struct {
	GoalID   unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Feedback FollowPath_Feedback             `yaml:"feedback"`
}

// NewFollowPath_FeedbackMessage creates a new FollowPath_FeedbackMessage with default values.
func NewFollowPath_FeedbackMessage() *FollowPath_FeedbackMessage {
	self := FollowPath_FeedbackMessage{}
	self.SetDefaults()
	return &self
}

func (t *FollowPath_FeedbackMessage) Clone() *FollowPath_FeedbackMessage {
	c := &FollowPath_FeedbackMessage{}
	c.GoalID = *t.GoalID.Clone()
	c.Feedback = *t.Feedback.Clone()
	return c
}

func (t *FollowPath_FeedbackMessage) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *FollowPath_FeedbackMessage) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Feedback.SetDefaults()
}

func (t *FollowPath_FeedbackMessage) GetTypeSupport() humble.MessageTypeSupport {
	return FollowPath_FeedbackMessageTypeSupport
}
func (t *FollowPath_FeedbackMessage) GetGoalID() *humble.GoalID {
	return (*humble.GoalID)(&t.GoalID.Uuid)
}

func (t *FollowPath_FeedbackMessage) SetGoalID(id *humble.GoalID) {
	t.GoalID.Uuid = *id
}

// FollowPath_FeedbackMessagePublisher wraps humble.Publisher to provide type safe helper
// functions
type FollowPath_FeedbackMessagePublisher struct {
	*humble.Publisher
}

// NewFollowPath_FeedbackMessagePublisher creates and returns a new publisher for the
// FollowPath_FeedbackMessage
func NewFollowPath_FeedbackMessagePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*FollowPath_FeedbackMessagePublisher, error) {
	pub, err := node.NewPublisher(topicName, FollowPath_FeedbackMessageTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowPath_FeedbackMessagePublisher{pub}, nil
}

func (p *FollowPath_FeedbackMessagePublisher) Publish(msg *FollowPath_FeedbackMessage) error {
	return p.Publisher.Publish(msg)
}

// FollowPath_FeedbackMessageSubscription wraps humble.Subscription to provide type safe helper
// functions
type FollowPath_FeedbackMessageSubscription struct {
	*humble.Subscription
}

// FollowPath_FeedbackMessageSubscriptionCallback type is used to provide a subscription
// handler function for a FollowPath_FeedbackMessageSubscription.
type FollowPath_FeedbackMessageSubscriptionCallback func(msg *FollowPath_FeedbackMessage, info *humble.MessageInfo, err error)

// NewFollowPath_FeedbackMessageSubscription creates and returns a new subscription for the
// FollowPath_FeedbackMessage
func NewFollowPath_FeedbackMessageSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback FollowPath_FeedbackMessageSubscriptionCallback) (*FollowPath_FeedbackMessageSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg FollowPath_FeedbackMessage
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, FollowPath_FeedbackMessageTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &FollowPath_FeedbackMessageSubscription{sub}, nil
}

func (s *FollowPath_FeedbackMessageSubscription) TakeMessage(out *FollowPath_FeedbackMessage) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneFollowPath_FeedbackMessageSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneFollowPath_FeedbackMessageSlice(dst, src []FollowPath_FeedbackMessage) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var FollowPath_FeedbackMessageTypeSupport humble.MessageTypeSupport = _FollowPath_FeedbackMessageTypeSupport{}

type _FollowPath_FeedbackMessageTypeSupport struct{}

func (t _FollowPath_FeedbackMessageTypeSupport) New() humble.Message {
	return NewFollowPath_FeedbackMessage()
}

func (t _FollowPath_FeedbackMessageTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.as2_msgs__action__FollowPath_FeedbackMessage
	return (unsafe.Pointer)(C.as2_msgs__action__FollowPath_FeedbackMessage__create())
}

func (t _FollowPath_FeedbackMessageTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.as2_msgs__action__FollowPath_FeedbackMessage__destroy((*C.as2_msgs__action__FollowPath_FeedbackMessage)(pointer_to_free))
}

func (t _FollowPath_FeedbackMessageTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*FollowPath_FeedbackMessage)
	mem := (*C.as2_msgs__action__FollowPath_FeedbackMessage)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	FollowPath_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&mem.feedback), &m.Feedback)
}

func (t _FollowPath_FeedbackMessageTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FollowPath_FeedbackMessage)
	mem := (*C.as2_msgs__action__FollowPath_FeedbackMessage)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	FollowPath_FeedbackTypeSupport.AsGoStruct(&m.Feedback, unsafe.Pointer(&mem.feedback))
}

func (t _FollowPath_FeedbackMessageTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__as2_msgs__action__FollowPath_FeedbackMessage())
}

type CFollowPath_FeedbackMessage = C.as2_msgs__action__FollowPath_FeedbackMessage
type CFollowPath_FeedbackMessageSequence = C.as2_msgs__action__FollowPath_FeedbackMessage__Sequence

func FollowPath_FeedbackMessageSequenceToGo(goSlice *[]FollowPath_FeedbackMessage, cSlice CFollowPath_FeedbackMessageSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FollowPath_FeedbackMessage, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		FollowPath_FeedbackMessageTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func FollowPath_FeedbackMessageSequenceToC(cSlice *CFollowPath_FeedbackMessageSequence, goSlice []FollowPath_FeedbackMessage) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.as2_msgs__action__FollowPath_FeedbackMessage)(C.malloc(C.sizeof_struct_as2_msgs__action__FollowPath_FeedbackMessage * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		FollowPath_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func FollowPath_FeedbackMessageArrayToGo(goSlice []FollowPath_FeedbackMessage, cSlice []CFollowPath_FeedbackMessage) {
	for i := 0; i < len(cSlice); i++ {
		FollowPath_FeedbackMessageTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func FollowPath_FeedbackMessageArrayToC(cSlice []CFollowPath_FeedbackMessage, goSlice []FollowPath_FeedbackMessage) {
	for i := 0; i < len(goSlice); i++ {
		FollowPath_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
