// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/follow_reference.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("as2_msgs/FollowReference_SendGoal", FollowReference_SendGoalTypeSupport)
	humble.RegisterService("as2_msgs/action/FollowReference_SendGoal", FollowReference_SendGoalTypeSupport)
}

type _FollowReference_SendGoalTypeSupport struct{}

func (s _FollowReference_SendGoalTypeSupport) Request() humble.MessageTypeSupport {
	return FollowReference_SendGoal_RequestTypeSupport
}

func (s _FollowReference_SendGoalTypeSupport) Response() humble.MessageTypeSupport {
	return FollowReference_SendGoal_ResponseTypeSupport
}

func (s _FollowReference_SendGoalTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__FollowReference_SendGoal())
}

// Modifying this variable is undefined behavior.
var FollowReference_SendGoalTypeSupport humble.ServiceTypeSupport = _FollowReference_SendGoalTypeSupport{}

// FollowReference_SendGoalClient wraps humble.Client to provide type safe helper
// functions
type FollowReference_SendGoalClient struct {
	*humble.Client
}

// NewFollowReference_SendGoalClient creates and returns a new client for the
// FollowReference_SendGoal
func NewFollowReference_SendGoalClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*FollowReference_SendGoalClient, error) {
	client, err := node.NewClient(serviceName, FollowReference_SendGoalTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &FollowReference_SendGoalClient{client}, nil
}

func (s *FollowReference_SendGoalClient) Send(ctx context.Context, req *FollowReference_SendGoal_Request) (*FollowReference_SendGoal_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*FollowReference_SendGoal_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type FollowReference_SendGoalServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s FollowReference_SendGoalServiceResponseSender) SendResponse(resp *FollowReference_SendGoal_Response) error {
	return s.sender.SendResponse(resp)
}

type FollowReference_SendGoalServiceRequestHandler func(*humble.ServiceInfo, *FollowReference_SendGoal_Request, FollowReference_SendGoalServiceResponseSender)

// FollowReference_SendGoalService wraps humble.Service to provide type safe helper
// functions
type FollowReference_SendGoalService struct {
	*humble.Service
}

// NewFollowReference_SendGoalService creates and returns a new service for the
// FollowReference_SendGoal
func NewFollowReference_SendGoalService(node *humble.Node, name string, options *humble.ServiceOptions, handler FollowReference_SendGoalServiceRequestHandler) (*FollowReference_SendGoalService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*FollowReference_SendGoal_Request)
		responseSender := FollowReference_SendGoalServiceResponseSender{sender: rs}
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, FollowReference_SendGoalTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &FollowReference_SendGoalService{service}, nil
}
