// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <as2_msgs/action/land.h>

*/
import "C"

func init() {
	humble.RegisterMessage("as2_msgs/Land_GetResult_Response", Land_GetResult_ResponseTypeSupport)
	humble.RegisterMessage("as2_msgs/action/Land_GetResult_Response", Land_GetResult_ResponseTypeSupport)
}

type Land_GetResult_Response struct {
	Status int8        `yaml:"status"`
	Result Land_Result `yaml:"result"`
}

// NewLand_GetResult_Response creates a new Land_GetResult_Response with default values.
func NewLand_GetResult_Response() *Land_GetResult_Response {
	self := Land_GetResult_Response{}
	self.SetDefaults()
	return &self
}

func (t *Land_GetResult_Response) Clone() *Land_GetResult_Response {
	c := &Land_GetResult_Response{}
	c.Status = t.Status
	c.Result = *t.Result.Clone()
	return c
}

func (t *Land_GetResult_Response) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *Land_GetResult_Response) SetDefaults() {
	t.Status = 0
	t.Result.SetDefaults()
}

func (t *Land_GetResult_Response) GetTypeSupport() humble.MessageTypeSupport {
	return Land_GetResult_ResponseTypeSupport
}

// Land_GetResult_ResponsePublisher wraps humble.Publisher to provide type safe helper
// functions
type Land_GetResult_ResponsePublisher struct {
	*humble.Publisher
}

// NewLand_GetResult_ResponsePublisher creates and returns a new publisher for the
// Land_GetResult_Response
func NewLand_GetResult_ResponsePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*Land_GetResult_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, Land_GetResult_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Land_GetResult_ResponsePublisher{pub}, nil
}

func (p *Land_GetResult_ResponsePublisher) Publish(msg *Land_GetResult_Response) error {
	return p.Publisher.Publish(msg)
}

// Land_GetResult_ResponseSubscription wraps humble.Subscription to provide type safe helper
// functions
type Land_GetResult_ResponseSubscription struct {
	*humble.Subscription
}

// Land_GetResult_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Land_GetResult_ResponseSubscription.
type Land_GetResult_ResponseSubscriptionCallback func(msg *Land_GetResult_Response, info *humble.MessageInfo, err error)

// NewLand_GetResult_ResponseSubscription creates and returns a new subscription for the
// Land_GetResult_Response
func NewLand_GetResult_ResponseSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback Land_GetResult_ResponseSubscriptionCallback) (*Land_GetResult_ResponseSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg Land_GetResult_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, Land_GetResult_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Land_GetResult_ResponseSubscription{sub}, nil
}

func (s *Land_GetResult_ResponseSubscription) TakeMessage(out *Land_GetResult_Response) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneLand_GetResult_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneLand_GetResult_ResponseSlice(dst, src []Land_GetResult_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Land_GetResult_ResponseTypeSupport humble.MessageTypeSupport = _Land_GetResult_ResponseTypeSupport{}

type _Land_GetResult_ResponseTypeSupport struct{}

func (t _Land_GetResult_ResponseTypeSupport) New() humble.Message {
	return NewLand_GetResult_Response()
}

func (t _Land_GetResult_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.as2_msgs__action__Land_GetResult_Response
	return (unsafe.Pointer)(C.as2_msgs__action__Land_GetResult_Response__create())
}

func (t _Land_GetResult_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.as2_msgs__action__Land_GetResult_Response__destroy((*C.as2_msgs__action__Land_GetResult_Response)(pointer_to_free))
}

func (t _Land_GetResult_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*Land_GetResult_Response)
	mem := (*C.as2_msgs__action__Land_GetResult_Response)(dst)
	mem.status = C.int8_t(m.Status)
	Land_ResultTypeSupport.AsCStruct(unsafe.Pointer(&mem.result), &m.Result)
}

func (t _Land_GetResult_ResponseTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Land_GetResult_Response)
	mem := (*C.as2_msgs__action__Land_GetResult_Response)(ros2_message_buffer)
	m.Status = int8(mem.status)
	Land_ResultTypeSupport.AsGoStruct(&m.Result, unsafe.Pointer(&mem.result))
}

func (t _Land_GetResult_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__as2_msgs__action__Land_GetResult_Response())
}

type CLand_GetResult_Response = C.as2_msgs__action__Land_GetResult_Response
type CLand_GetResult_ResponseSequence = C.as2_msgs__action__Land_GetResult_Response__Sequence

func Land_GetResult_ResponseSequenceToGo(goSlice *[]Land_GetResult_Response, cSlice CLand_GetResult_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Land_GetResult_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Land_GetResult_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func Land_GetResult_ResponseSequenceToC(cSlice *CLand_GetResult_ResponseSequence, goSlice []Land_GetResult_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.as2_msgs__action__Land_GetResult_Response)(C.malloc(C.sizeof_struct_as2_msgs__action__Land_GetResult_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Land_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func Land_GetResult_ResponseArrayToGo(goSlice []Land_GetResult_Response, cSlice []CLand_GetResult_Response) {
	for i := 0; i < len(cSlice); i++ {
		Land_GetResult_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func Land_GetResult_ResponseArrayToC(cSlice []CLand_GetResult_Response, goSlice []Land_GetResult_Response) {
	for i := 0; i < len(goSlice); i++ {
		Land_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
