// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	unique_identifier_msgs_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/unique_identifier_msgs/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <as2_msgs/action/navigate_to_point.h>

*/
import "C"

func init() {
	humble.RegisterMessage("as2_msgs/NavigateToPoint_FeedbackMessage", NavigateToPoint_FeedbackMessageTypeSupport)
	humble.RegisterMessage("as2_msgs/action/NavigateToPoint_FeedbackMessage", NavigateToPoint_FeedbackMessageTypeSupport)
}

type NavigateToPoint_FeedbackMessage struct {
	GoalID unique_identifier_msgs_msg.UUID `yaml:"goal_id"`
	Feedback NavigateToPoint_Feedback `yaml:"feedback"`
}

// NewNavigateToPoint_FeedbackMessage creates a new NavigateToPoint_FeedbackMessage with default values.
func NewNavigateToPoint_FeedbackMessage() *NavigateToPoint_FeedbackMessage {
	self := NavigateToPoint_FeedbackMessage{}
	self.SetDefaults()
	return &self
}

func (t *NavigateToPoint_FeedbackMessage) Clone() *NavigateToPoint_FeedbackMessage {
	c := &NavigateToPoint_FeedbackMessage{}
	c.GoalID = *t.GoalID.Clone()
	c.Feedback = *t.Feedback.Clone()
	return c
}

func (t *NavigateToPoint_FeedbackMessage) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *NavigateToPoint_FeedbackMessage) SetDefaults() {
	t.GoalID.SetDefaults()
	t.Feedback.SetDefaults()
}

func (t *NavigateToPoint_FeedbackMessage) GetTypeSupport() humble.MessageTypeSupport {
	return NavigateToPoint_FeedbackMessageTypeSupport
}
func (t *NavigateToPoint_FeedbackMessage) GetGoalID() *humble.GoalID {
	return (*humble.GoalID)(&t.GoalID.Uuid)
}

func (t *NavigateToPoint_FeedbackMessage) SetGoalID(id *humble.GoalID) {
	t.GoalID.Uuid = *id
}

// NavigateToPoint_FeedbackMessagePublisher wraps humble.Publisher to provide type safe helper
// functions
type NavigateToPoint_FeedbackMessagePublisher struct {
	*humble.Publisher
}

// NewNavigateToPoint_FeedbackMessagePublisher creates and returns a new publisher for the
// NavigateToPoint_FeedbackMessage
func NewNavigateToPoint_FeedbackMessagePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*NavigateToPoint_FeedbackMessagePublisher, error) {
	pub, err := node.NewPublisher(topicName, NavigateToPoint_FeedbackMessageTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &NavigateToPoint_FeedbackMessagePublisher{pub}, nil
}

func (p *NavigateToPoint_FeedbackMessagePublisher) Publish(msg *NavigateToPoint_FeedbackMessage) error {
	return p.Publisher.Publish(msg)
}

// NavigateToPoint_FeedbackMessageSubscription wraps humble.Subscription to provide type safe helper
// functions
type NavigateToPoint_FeedbackMessageSubscription struct {
	*humble.Subscription
}

// NavigateToPoint_FeedbackMessageSubscriptionCallback type is used to provide a subscription
// handler function for a NavigateToPoint_FeedbackMessageSubscription.
type NavigateToPoint_FeedbackMessageSubscriptionCallback func(msg *NavigateToPoint_FeedbackMessage, info *humble.MessageInfo, err error)

// NewNavigateToPoint_FeedbackMessageSubscription creates and returns a new subscription for the
// NavigateToPoint_FeedbackMessage
func NewNavigateToPoint_FeedbackMessageSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback NavigateToPoint_FeedbackMessageSubscriptionCallback) (*NavigateToPoint_FeedbackMessageSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg NavigateToPoint_FeedbackMessage
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, NavigateToPoint_FeedbackMessageTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &NavigateToPoint_FeedbackMessageSubscription{sub}, nil
}

func (s *NavigateToPoint_FeedbackMessageSubscription) TakeMessage(out *NavigateToPoint_FeedbackMessage) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneNavigateToPoint_FeedbackMessageSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneNavigateToPoint_FeedbackMessageSlice(dst, src []NavigateToPoint_FeedbackMessage) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var NavigateToPoint_FeedbackMessageTypeSupport humble.MessageTypeSupport = _NavigateToPoint_FeedbackMessageTypeSupport{}

type _NavigateToPoint_FeedbackMessageTypeSupport struct{}

func (t _NavigateToPoint_FeedbackMessageTypeSupport) New() humble.Message {
	return NewNavigateToPoint_FeedbackMessage()
}

func (t _NavigateToPoint_FeedbackMessageTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.as2_msgs__action__NavigateToPoint_FeedbackMessage
	return (unsafe.Pointer)(C.as2_msgs__action__NavigateToPoint_FeedbackMessage__create())
}

func (t _NavigateToPoint_FeedbackMessageTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.as2_msgs__action__NavigateToPoint_FeedbackMessage__destroy((*C.as2_msgs__action__NavigateToPoint_FeedbackMessage)(pointer_to_free))
}

func (t _NavigateToPoint_FeedbackMessageTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*NavigateToPoint_FeedbackMessage)
	mem := (*C.as2_msgs__action__NavigateToPoint_FeedbackMessage)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.goal_id), &m.GoalID)
	NavigateToPoint_FeedbackTypeSupport.AsCStruct(unsafe.Pointer(&mem.feedback), &m.Feedback)
}

func (t _NavigateToPoint_FeedbackMessageTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*NavigateToPoint_FeedbackMessage)
	mem := (*C.as2_msgs__action__NavigateToPoint_FeedbackMessage)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.GoalID, unsafe.Pointer(&mem.goal_id))
	NavigateToPoint_FeedbackTypeSupport.AsGoStruct(&m.Feedback, unsafe.Pointer(&mem.feedback))
}

func (t _NavigateToPoint_FeedbackMessageTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__as2_msgs__action__NavigateToPoint_FeedbackMessage())
}

type CNavigateToPoint_FeedbackMessage = C.as2_msgs__action__NavigateToPoint_FeedbackMessage
type CNavigateToPoint_FeedbackMessageSequence = C.as2_msgs__action__NavigateToPoint_FeedbackMessage__Sequence

func NavigateToPoint_FeedbackMessageSequenceToGo(goSlice *[]NavigateToPoint_FeedbackMessage, cSlice CNavigateToPoint_FeedbackMessageSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]NavigateToPoint_FeedbackMessage, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		NavigateToPoint_FeedbackMessageTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func NavigateToPoint_FeedbackMessageSequenceToC(cSlice *CNavigateToPoint_FeedbackMessageSequence, goSlice []NavigateToPoint_FeedbackMessage) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.as2_msgs__action__NavigateToPoint_FeedbackMessage)(C.malloc(C.sizeof_struct_as2_msgs__action__NavigateToPoint_FeedbackMessage * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		NavigateToPoint_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func NavigateToPoint_FeedbackMessageArrayToGo(goSlice []NavigateToPoint_FeedbackMessage, cSlice []CNavigateToPoint_FeedbackMessage) {
	for i := 0; i < len(cSlice); i++ {
		NavigateToPoint_FeedbackMessageTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func NavigateToPoint_FeedbackMessageArrayToC(cSlice []CNavigateToPoint_FeedbackMessage, goSlice []NavigateToPoint_FeedbackMessage) {
	for i := 0; i < len(goSlice); i++ {
		NavigateToPoint_FeedbackMessageTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
