// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

/*
#include <rosidl_runtime_c/message_type_support_struct.h>
#include <as2_msgs/action/set_arming_state.h>
*/
import "C"

import (
	"context"
	"errors"
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

func init() {
	humble.RegisterService("as2_msgs/SetArmingState_GetResult", SetArmingState_GetResultTypeSupport)
	humble.RegisterService("as2_msgs/action/SetArmingState_GetResult", SetArmingState_GetResultTypeSupport)
}

type _SetArmingState_GetResultTypeSupport struct {}

func (s _SetArmingState_GetResultTypeSupport) Request() humble.MessageTypeSupport {
	return SetArmingState_GetResult_RequestTypeSupport
}

func (s _SetArmingState_GetResultTypeSupport) Response() humble.MessageTypeSupport {
	return SetArmingState_GetResult_ResponseTypeSupport
}

func (s _SetArmingState_GetResultTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__as2_msgs__action__SetArmingState_GetResult())
}

// Modifying this variable is undefined behavior.
var SetArmingState_GetResultTypeSupport humble.ServiceTypeSupport = _SetArmingState_GetResultTypeSupport{}

// SetArmingState_GetResultClient wraps humble.Client to provide type safe helper
// functions
type SetArmingState_GetResultClient struct {
	*humble.Client
}

// NewSetArmingState_GetResultClient creates and returns a new client for the
// SetArmingState_GetResult
func NewSetArmingState_GetResultClient(node *humble.Node, serviceName string, options *humble.ClientOptions) (*SetArmingState_GetResultClient, error) {
	client, err := node.NewClient(serviceName, SetArmingState_GetResultTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetArmingState_GetResultClient{client}, nil
}

func (s *SetArmingState_GetResultClient) Send(ctx context.Context, req *SetArmingState_GetResult_Request) (*SetArmingState_GetResult_Response, *humble.ServiceInfo, error) {
	msg, rmw, err := s.Client.Send(ctx, req)
	if err != nil {
		return nil, rmw, err
	}
	typedMessage, ok := msg.(*SetArmingState_GetResult_Response)
	if !ok {
		return nil, rmw, errors.New("invalid message type returned")
	}
	return typedMessage, rmw, err
}

type SetArmingState_GetResultServiceResponseSender struct {
	sender humble.ServiceResponseSender
}

func (s SetArmingState_GetResultServiceResponseSender) SendResponse(resp *SetArmingState_GetResult_Response) error {
	return s.sender.SendResponse(resp)
}

type SetArmingState_GetResultServiceRequestHandler func(*humble.ServiceInfo, *SetArmingState_GetResult_Request, SetArmingState_GetResultServiceResponseSender)

// SetArmingState_GetResultService wraps humble.Service to provide type safe helper
// functions
type SetArmingState_GetResultService struct {
	*humble.Service
}

// NewSetArmingState_GetResultService creates and returns a new service for the
// SetArmingState_GetResult
func NewSetArmingState_GetResultService(node *humble.Node, name string, options *humble.ServiceOptions, handler SetArmingState_GetResultServiceRequestHandler) (*SetArmingState_GetResultService, error) {
	h := func(rmw *humble.ServiceInfo, msg humble.Message, rs humble.ServiceResponseSender) {
		m := msg.(*SetArmingState_GetResult_Request)
		responseSender := SetArmingState_GetResultServiceResponseSender{sender: rs} 
		handler(rmw, m, responseSender)
	}
	service, err := node.NewService(name, SetArmingState_GetResultTypeSupport, options, h)
	if err != nil {
		return nil, err
	}
	return &SetArmingState_GetResultService{service}, nil
}