// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action

import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
)

/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <as2_msgs/action/set_arming_state.h>

*/
import "C"

func init() {
	humble.RegisterMessage("as2_msgs/SetArmingState_GetResult_Response", SetArmingState_GetResult_ResponseTypeSupport)
	humble.RegisterMessage("as2_msgs/action/SetArmingState_GetResult_Response", SetArmingState_GetResult_ResponseTypeSupport)
}

type SetArmingState_GetResult_Response struct {
	Status int8                  `yaml:"status"`
	Result SetArmingState_Result `yaml:"result"`
}

// NewSetArmingState_GetResult_Response creates a new SetArmingState_GetResult_Response with default values.
func NewSetArmingState_GetResult_Response() *SetArmingState_GetResult_Response {
	self := SetArmingState_GetResult_Response{}
	self.SetDefaults()
	return &self
}

func (t *SetArmingState_GetResult_Response) Clone() *SetArmingState_GetResult_Response {
	c := &SetArmingState_GetResult_Response{}
	c.Status = t.Status
	c.Result = *t.Result.Clone()
	return c
}

func (t *SetArmingState_GetResult_Response) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *SetArmingState_GetResult_Response) SetDefaults() {
	t.Status = 0
	t.Result.SetDefaults()
}

func (t *SetArmingState_GetResult_Response) GetTypeSupport() humble.MessageTypeSupport {
	return SetArmingState_GetResult_ResponseTypeSupport
}

// SetArmingState_GetResult_ResponsePublisher wraps humble.Publisher to provide type safe helper
// functions
type SetArmingState_GetResult_ResponsePublisher struct {
	*humble.Publisher
}

// NewSetArmingState_GetResult_ResponsePublisher creates and returns a new publisher for the
// SetArmingState_GetResult_Response
func NewSetArmingState_GetResult_ResponsePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*SetArmingState_GetResult_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, SetArmingState_GetResult_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &SetArmingState_GetResult_ResponsePublisher{pub}, nil
}

func (p *SetArmingState_GetResult_ResponsePublisher) Publish(msg *SetArmingState_GetResult_Response) error {
	return p.Publisher.Publish(msg)
}

// SetArmingState_GetResult_ResponseSubscription wraps humble.Subscription to provide type safe helper
// functions
type SetArmingState_GetResult_ResponseSubscription struct {
	*humble.Subscription
}

// SetArmingState_GetResult_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a SetArmingState_GetResult_ResponseSubscription.
type SetArmingState_GetResult_ResponseSubscriptionCallback func(msg *SetArmingState_GetResult_Response, info *humble.MessageInfo, err error)

// NewSetArmingState_GetResult_ResponseSubscription creates and returns a new subscription for the
// SetArmingState_GetResult_Response
func NewSetArmingState_GetResult_ResponseSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback SetArmingState_GetResult_ResponseSubscriptionCallback) (*SetArmingState_GetResult_ResponseSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg SetArmingState_GetResult_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, SetArmingState_GetResult_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &SetArmingState_GetResult_ResponseSubscription{sub}, nil
}

func (s *SetArmingState_GetResult_ResponseSubscription) TakeMessage(out *SetArmingState_GetResult_Response) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneSetArmingState_GetResult_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetArmingState_GetResult_ResponseSlice(dst, src []SetArmingState_GetResult_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetArmingState_GetResult_ResponseTypeSupport humble.MessageTypeSupport = _SetArmingState_GetResult_ResponseTypeSupport{}

type _SetArmingState_GetResult_ResponseTypeSupport struct{}

func (t _SetArmingState_GetResult_ResponseTypeSupport) New() humble.Message {
	return NewSetArmingState_GetResult_Response()
}

func (t _SetArmingState_GetResult_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.as2_msgs__action__SetArmingState_GetResult_Response
	return (unsafe.Pointer)(C.as2_msgs__action__SetArmingState_GetResult_Response__create())
}

func (t _SetArmingState_GetResult_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.as2_msgs__action__SetArmingState_GetResult_Response__destroy((*C.as2_msgs__action__SetArmingState_GetResult_Response)(pointer_to_free))
}

func (t _SetArmingState_GetResult_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*SetArmingState_GetResult_Response)
	mem := (*C.as2_msgs__action__SetArmingState_GetResult_Response)(dst)
	mem.status = C.int8_t(m.Status)
	SetArmingState_ResultTypeSupport.AsCStruct(unsafe.Pointer(&mem.result), &m.Result)
}

func (t _SetArmingState_GetResult_ResponseTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetArmingState_GetResult_Response)
	mem := (*C.as2_msgs__action__SetArmingState_GetResult_Response)(ros2_message_buffer)
	m.Status = int8(mem.status)
	SetArmingState_ResultTypeSupport.AsGoStruct(&m.Result, unsafe.Pointer(&mem.result))
}

func (t _SetArmingState_GetResult_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__as2_msgs__action__SetArmingState_GetResult_Response())
}

type CSetArmingState_GetResult_Response = C.as2_msgs__action__SetArmingState_GetResult_Response
type CSetArmingState_GetResult_ResponseSequence = C.as2_msgs__action__SetArmingState_GetResult_Response__Sequence

func SetArmingState_GetResult_ResponseSequenceToGo(goSlice *[]SetArmingState_GetResult_Response, cSlice CSetArmingState_GetResult_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetArmingState_GetResult_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		SetArmingState_GetResult_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func SetArmingState_GetResult_ResponseSequenceToC(cSlice *CSetArmingState_GetResult_ResponseSequence, goSlice []SetArmingState_GetResult_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.as2_msgs__action__SetArmingState_GetResult_Response)(C.malloc(C.sizeof_struct_as2_msgs__action__SetArmingState_GetResult_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		SetArmingState_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func SetArmingState_GetResult_ResponseArrayToGo(goSlice []SetArmingState_GetResult_Response, cSlice []CSetArmingState_GetResult_Response) {
	for i := 0; i < len(cSlice); i++ {
		SetArmingState_GetResult_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func SetArmingState_GetResult_ResponseArrayToC(cSlice []CSetArmingState_GetResult_Response, goSlice []SetArmingState_GetResult_Response) {
	for i := 0; i < len(goSlice); i++ {
		SetArmingState_GetResult_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
