// Code generated by ros2gen. DO NOT EDIT.

package as2_msgs_action
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	builtin_interfaces_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <as2_msgs/action/takeoff.h>

*/
import "C"

func init() {
	humble.RegisterMessage("as2_msgs/Takeoff_SendGoal_Response", Takeoff_SendGoal_ResponseTypeSupport)
	humble.RegisterMessage("as2_msgs/action/Takeoff_SendGoal_Response", Takeoff_SendGoal_ResponseTypeSupport)
}

type Takeoff_SendGoal_Response struct {
	Accepted bool `yaml:"accepted"`
	Stamp builtin_interfaces_msg.Time `yaml:"stamp"`
}

// NewTakeoff_SendGoal_Response creates a new Takeoff_SendGoal_Response with default values.
func NewTakeoff_SendGoal_Response() *Takeoff_SendGoal_Response {
	self := Takeoff_SendGoal_Response{}
	self.SetDefaults()
	return &self
}

func (t *Takeoff_SendGoal_Response) Clone() *Takeoff_SendGoal_Response {
	c := &Takeoff_SendGoal_Response{}
	c.Accepted = t.Accepted
	c.Stamp = *t.Stamp.Clone()
	return c
}

func (t *Takeoff_SendGoal_Response) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *Takeoff_SendGoal_Response) SetDefaults() {
	t.Accepted = false
	t.Stamp.SetDefaults()
}

func (t *Takeoff_SendGoal_Response) GetTypeSupport() humble.MessageTypeSupport {
	return Takeoff_SendGoal_ResponseTypeSupport
}
func (t *Takeoff_SendGoal_Response) GetGoalAccepted() bool {
	return t.Accepted
}

// Takeoff_SendGoal_ResponsePublisher wraps humble.Publisher to provide type safe helper
// functions
type Takeoff_SendGoal_ResponsePublisher struct {
	*humble.Publisher
}

// NewTakeoff_SendGoal_ResponsePublisher creates and returns a new publisher for the
// Takeoff_SendGoal_Response
func NewTakeoff_SendGoal_ResponsePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*Takeoff_SendGoal_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, Takeoff_SendGoal_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &Takeoff_SendGoal_ResponsePublisher{pub}, nil
}

func (p *Takeoff_SendGoal_ResponsePublisher) Publish(msg *Takeoff_SendGoal_Response) error {
	return p.Publisher.Publish(msg)
}

// Takeoff_SendGoal_ResponseSubscription wraps humble.Subscription to provide type safe helper
// functions
type Takeoff_SendGoal_ResponseSubscription struct {
	*humble.Subscription
}

// Takeoff_SendGoal_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a Takeoff_SendGoal_ResponseSubscription.
type Takeoff_SendGoal_ResponseSubscriptionCallback func(msg *Takeoff_SendGoal_Response, info *humble.MessageInfo, err error)

// NewTakeoff_SendGoal_ResponseSubscription creates and returns a new subscription for the
// Takeoff_SendGoal_Response
func NewTakeoff_SendGoal_ResponseSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback Takeoff_SendGoal_ResponseSubscriptionCallback) (*Takeoff_SendGoal_ResponseSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg Takeoff_SendGoal_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, Takeoff_SendGoal_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &Takeoff_SendGoal_ResponseSubscription{sub}, nil
}

func (s *Takeoff_SendGoal_ResponseSubscription) TakeMessage(out *Takeoff_SendGoal_Response) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneTakeoff_SendGoal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneTakeoff_SendGoal_ResponseSlice(dst, src []Takeoff_SendGoal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Takeoff_SendGoal_ResponseTypeSupport humble.MessageTypeSupport = _Takeoff_SendGoal_ResponseTypeSupport{}

type _Takeoff_SendGoal_ResponseTypeSupport struct{}

func (t _Takeoff_SendGoal_ResponseTypeSupport) New() humble.Message {
	return NewTakeoff_SendGoal_Response()
}

func (t _Takeoff_SendGoal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.as2_msgs__action__Takeoff_SendGoal_Response
	return (unsafe.Pointer)(C.as2_msgs__action__Takeoff_SendGoal_Response__create())
}

func (t _Takeoff_SendGoal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.as2_msgs__action__Takeoff_SendGoal_Response__destroy((*C.as2_msgs__action__Takeoff_SendGoal_Response)(pointer_to_free))
}

func (t _Takeoff_SendGoal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*Takeoff_SendGoal_Response)
	mem := (*C.as2_msgs__action__Takeoff_SendGoal_Response)(dst)
	mem.accepted = C.bool(m.Accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.stamp), &m.Stamp)
}

func (t _Takeoff_SendGoal_ResponseTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Takeoff_SendGoal_Response)
	mem := (*C.as2_msgs__action__Takeoff_SendGoal_Response)(ros2_message_buffer)
	m.Accepted = bool(mem.accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Stamp, unsafe.Pointer(&mem.stamp))
}

func (t _Takeoff_SendGoal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__as2_msgs__action__Takeoff_SendGoal_Response())
}

type CTakeoff_SendGoal_Response = C.as2_msgs__action__Takeoff_SendGoal_Response
type CTakeoff_SendGoal_ResponseSequence = C.as2_msgs__action__Takeoff_SendGoal_Response__Sequence

func Takeoff_SendGoal_ResponseSequenceToGo(goSlice *[]Takeoff_SendGoal_Response, cSlice CTakeoff_SendGoal_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Takeoff_SendGoal_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		Takeoff_SendGoal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func Takeoff_SendGoal_ResponseSequenceToC(cSlice *CTakeoff_SendGoal_ResponseSequence, goSlice []Takeoff_SendGoal_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.as2_msgs__action__Takeoff_SendGoal_Response)(C.malloc(C.sizeof_struct_as2_msgs__action__Takeoff_SendGoal_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		Takeoff_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func Takeoff_SendGoal_ResponseArrayToGo(goSlice []Takeoff_SendGoal_Response, cSlice []CTakeoff_SendGoal_Response) {
	for i := 0; i < len(cSlice); i++ {
		Takeoff_SendGoal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func Takeoff_SendGoal_ResponseArrayToC(cSlice []CTakeoff_SendGoal_Response, goSlice []Takeoff_SendGoal_Response) {
	for i := 0; i < len(goSlice); i++ {
		Takeoff_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
