// Code generated by ros2gen. DO NOT EDIT.

package geometry_msgs_msg
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geometry_msgs/msg/quaternion.h>

*/
import "C"

func init() {
	humble.RegisterMessage("geometry_msgs/Quaternion", QuaternionTypeSupport)
	humble.RegisterMessage("geometry_msgs/msg/Quaternion", QuaternionTypeSupport)
}

type Quaternion struct {
	X float64 `yaml:"x"`
	Y float64 `yaml:"y"`
	Z float64 `yaml:"z"`
	W float64 `yaml:"w"`
}

// NewQuaternion creates a new Quaternion with default values.
func NewQuaternion() *Quaternion {
	self := Quaternion{}
	self.SetDefaults()
	return &self
}

func (t *Quaternion) Clone() *Quaternion {
	c := &Quaternion{}
	c.X = t.X
	c.Y = t.Y
	c.Z = t.Z
	c.W = t.W
	return c
}

func (t *Quaternion) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *Quaternion) SetDefaults() {
	t.X = 0
	t.Y = 0
	t.Z = 0
	t.W = 1
}

func (t *Quaternion) GetTypeSupport() humble.MessageTypeSupport {
	return QuaternionTypeSupport
}

// QuaternionPublisher wraps humble.Publisher to provide type safe helper
// functions
type QuaternionPublisher struct {
	*humble.Publisher
}

// NewQuaternionPublisher creates and returns a new publisher for the
// Quaternion
func NewQuaternionPublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*QuaternionPublisher, error) {
	pub, err := node.NewPublisher(topicName, QuaternionTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &QuaternionPublisher{pub}, nil
}

func (p *QuaternionPublisher) Publish(msg *Quaternion) error {
	return p.Publisher.Publish(msg)
}

// QuaternionSubscription wraps humble.Subscription to provide type safe helper
// functions
type QuaternionSubscription struct {
	*humble.Subscription
}

// QuaternionSubscriptionCallback type is used to provide a subscription
// handler function for a QuaternionSubscription.
type QuaternionSubscriptionCallback func(msg *Quaternion, info *humble.MessageInfo, err error)

// NewQuaternionSubscription creates and returns a new subscription for the
// Quaternion
func NewQuaternionSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback QuaternionSubscriptionCallback) (*QuaternionSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg Quaternion
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, QuaternionTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &QuaternionSubscription{sub}, nil
}

func (s *QuaternionSubscription) TakeMessage(out *Quaternion) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneQuaternionSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneQuaternionSlice(dst, src []Quaternion) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var QuaternionTypeSupport humble.MessageTypeSupport = _QuaternionTypeSupport{}

type _QuaternionTypeSupport struct{}

func (t _QuaternionTypeSupport) New() humble.Message {
	return NewQuaternion()
}

func (t _QuaternionTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geometry_msgs__msg__Quaternion
	return (unsafe.Pointer)(C.geometry_msgs__msg__Quaternion__create())
}

func (t _QuaternionTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geometry_msgs__msg__Quaternion__destroy((*C.geometry_msgs__msg__Quaternion)(pointer_to_free))
}

func (t _QuaternionTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*Quaternion)
	mem := (*C.geometry_msgs__msg__Quaternion)(dst)
	mem.x = C.double(m.X)
	mem.y = C.double(m.Y)
	mem.z = C.double(m.Z)
	mem.w = C.double(m.W)
}

func (t _QuaternionTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Quaternion)
	mem := (*C.geometry_msgs__msg__Quaternion)(ros2_message_buffer)
	m.X = float64(mem.x)
	m.Y = float64(mem.y)
	m.Z = float64(mem.z)
	m.W = float64(mem.w)
}

func (t _QuaternionTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geometry_msgs__msg__Quaternion())
}

type CQuaternion = C.geometry_msgs__msg__Quaternion
type CQuaternionSequence = C.geometry_msgs__msg__Quaternion__Sequence

func QuaternionSequenceToGo(goSlice *[]Quaternion, cSlice CQuaternionSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Quaternion, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		QuaternionTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func QuaternionSequenceToC(cSlice *CQuaternionSequence, goSlice []Quaternion) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.geometry_msgs__msg__Quaternion)(C.malloc(C.sizeof_struct_geometry_msgs__msg__Quaternion * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		QuaternionTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func QuaternionArrayToGo(goSlice []Quaternion, cSlice []CQuaternion) {
	for i := 0; i < len(cSlice); i++ {
		QuaternionTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func QuaternionArrayToC(cSlice []CQuaternion, goSlice []Quaternion) {
	for i := 0; i < len(goSlice); i++ {
		QuaternionTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
