// Code generated by ros2gen. DO NOT EDIT.

package tf2_msgs_action
import (
	"unsafe"

	"github.com/okieraised/rclgo/humble"
	builtin_interfaces_msg "github.com/okieraised/monitoring-agent/internal/ros_msgs/builtin_interfaces/msg"
	
)
/*
#include <rosidl_runtime_c/message_type_support_struct.h>

#include <tf2_msgs/action/lookup_transform.h>

*/
import "C"

func init() {
	humble.RegisterMessage("tf2_msgs/LookupTransform_SendGoal_Response", LookupTransform_SendGoal_ResponseTypeSupport)
	humble.RegisterMessage("tf2_msgs/action/LookupTransform_SendGoal_Response", LookupTransform_SendGoal_ResponseTypeSupport)
}

type LookupTransform_SendGoal_Response struct {
	Accepted bool `yaml:"accepted"`
	Stamp builtin_interfaces_msg.Time `yaml:"stamp"`
}

// NewLookupTransform_SendGoal_Response creates a new LookupTransform_SendGoal_Response with default values.
func NewLookupTransform_SendGoal_Response() *LookupTransform_SendGoal_Response {
	self := LookupTransform_SendGoal_Response{}
	self.SetDefaults()
	return &self
}

func (t *LookupTransform_SendGoal_Response) Clone() *LookupTransform_SendGoal_Response {
	c := &LookupTransform_SendGoal_Response{}
	c.Accepted = t.Accepted
	c.Stamp = *t.Stamp.Clone()
	return c
}

func (t *LookupTransform_SendGoal_Response) CloneMsg() humble.Message {
	return t.Clone()
}

func (t *LookupTransform_SendGoal_Response) SetDefaults() {
	t.Accepted = false
	t.Stamp.SetDefaults()
}

func (t *LookupTransform_SendGoal_Response) GetTypeSupport() humble.MessageTypeSupport {
	return LookupTransform_SendGoal_ResponseTypeSupport
}
func (t *LookupTransform_SendGoal_Response) GetGoalAccepted() bool {
	return t.Accepted
}

// LookupTransform_SendGoal_ResponsePublisher wraps humble.Publisher to provide type safe helper
// functions
type LookupTransform_SendGoal_ResponsePublisher struct {
	*humble.Publisher
}

// NewLookupTransform_SendGoal_ResponsePublisher creates and returns a new publisher for the
// LookupTransform_SendGoal_Response
func NewLookupTransform_SendGoal_ResponsePublisher(node *humble.Node, topicName string, options *humble.PublisherOptions) (*LookupTransform_SendGoal_ResponsePublisher, error) {
	pub, err := node.NewPublisher(topicName, LookupTransform_SendGoal_ResponseTypeSupport, options)
	if err != nil {
		return nil, err
	}
	return &LookupTransform_SendGoal_ResponsePublisher{pub}, nil
}

func (p *LookupTransform_SendGoal_ResponsePublisher) Publish(msg *LookupTransform_SendGoal_Response) error {
	return p.Publisher.Publish(msg)
}

// LookupTransform_SendGoal_ResponseSubscription wraps humble.Subscription to provide type safe helper
// functions
type LookupTransform_SendGoal_ResponseSubscription struct {
	*humble.Subscription
}

// LookupTransform_SendGoal_ResponseSubscriptionCallback type is used to provide a subscription
// handler function for a LookupTransform_SendGoal_ResponseSubscription.
type LookupTransform_SendGoal_ResponseSubscriptionCallback func(msg *LookupTransform_SendGoal_Response, info *humble.MessageInfo, err error)

// NewLookupTransform_SendGoal_ResponseSubscription creates and returns a new subscription for the
// LookupTransform_SendGoal_Response
func NewLookupTransform_SendGoal_ResponseSubscription(node *humble.Node, topicName string, opts *humble.SubscriptionOptions, subscriptionCallback LookupTransform_SendGoal_ResponseSubscriptionCallback) (*LookupTransform_SendGoal_ResponseSubscription, error) {
	callback := func(s *humble.Subscription) {
		var msg LookupTransform_SendGoal_Response
		info, err := s.TakeMessage(&msg)
		subscriptionCallback(&msg, info, err)
	}
	sub, err := node.NewSubscription(topicName, LookupTransform_SendGoal_ResponseTypeSupport, opts, callback)
	if err != nil {
		return nil, err
	}
	return &LookupTransform_SendGoal_ResponseSubscription{sub}, nil
}

func (s *LookupTransform_SendGoal_ResponseSubscription) TakeMessage(out *LookupTransform_SendGoal_Response) (*humble.MessageInfo, error) {
	return s.Subscription.TakeMessage(out)
}

// CloneLookupTransform_SendGoal_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneLookupTransform_SendGoal_ResponseSlice(dst, src []LookupTransform_SendGoal_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var LookupTransform_SendGoal_ResponseTypeSupport humble.MessageTypeSupport = _LookupTransform_SendGoal_ResponseTypeSupport{}

type _LookupTransform_SendGoal_ResponseTypeSupport struct{}

func (t _LookupTransform_SendGoal_ResponseTypeSupport) New() humble.Message {
	return NewLookupTransform_SendGoal_Response()
}

func (t _LookupTransform_SendGoal_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.tf2_msgs__action__LookupTransform_SendGoal_Response
	return (unsafe.Pointer)(C.tf2_msgs__action__LookupTransform_SendGoal_Response__create())
}

func (t _LookupTransform_SendGoal_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.tf2_msgs__action__LookupTransform_SendGoal_Response__destroy((*C.tf2_msgs__action__LookupTransform_SendGoal_Response)(pointer_to_free))
}

func (t _LookupTransform_SendGoal_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg humble.Message) {
	m := msg.(*LookupTransform_SendGoal_Response)
	mem := (*C.tf2_msgs__action__LookupTransform_SendGoal_Response)(dst)
	mem.accepted = C.bool(m.Accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.stamp), &m.Stamp)
}

func (t _LookupTransform_SendGoal_ResponseTypeSupport) AsGoStruct(msg humble.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*LookupTransform_SendGoal_Response)
	mem := (*C.tf2_msgs__action__LookupTransform_SendGoal_Response)(ros2_message_buffer)
	m.Accepted = bool(mem.accepted)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Stamp, unsafe.Pointer(&mem.stamp))
}

func (t _LookupTransform_SendGoal_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__tf2_msgs__action__LookupTransform_SendGoal_Response())
}

type CLookupTransform_SendGoal_Response = C.tf2_msgs__action__LookupTransform_SendGoal_Response
type CLookupTransform_SendGoal_ResponseSequence = C.tf2_msgs__action__LookupTransform_SendGoal_Response__Sequence

func LookupTransform_SendGoal_ResponseSequenceToGo(goSlice *[]LookupTransform_SendGoal_Response, cSlice CLookupTransform_SendGoal_ResponseSequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]LookupTransform_SendGoal_Response, cSlice.size)
	src := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range src {
		LookupTransform_SendGoal_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(&src[i]))
	}
}

func LookupTransform_SendGoal_ResponseSequenceToC(cSlice *CLookupTransform_SendGoal_ResponseSequence, goSlice []LookupTransform_SendGoal_Response) {
	if len(goSlice) == 0 {
		cSlice.data = nil
		cSlice.capacity = 0
		cSlice.size = 0
		return
	}
	cSlice.data = (*C.tf2_msgs__action__LookupTransform_SendGoal_Response)(C.malloc(C.sizeof_struct_tf2_msgs__action__LookupTransform_SendGoal_Response * C.size_t(len(goSlice))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity
	dst := unsafe.Slice(cSlice.data, cSlice.size)
	for i := range goSlice {
		LookupTransform_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&dst[i]), &goSlice[i])
	}
}

func LookupTransform_SendGoal_ResponseArrayToGo(goSlice []LookupTransform_SendGoal_Response, cSlice []CLookupTransform_SendGoal_Response) {
	for i := 0; i < len(cSlice); i++ {
		LookupTransform_SendGoal_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}

func LookupTransform_SendGoal_ResponseArrayToC(cSlice []CLookupTransform_SendGoal_Response, goSlice []LookupTransform_SendGoal_Response) {
	for i := 0; i < len(goSlice); i++ {
		LookupTransform_SendGoal_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
